local PLUGIN = PLUGIN;

Schema.voices:Add("Combine", "0", "Zero.", "npc/combine_soldier/vo/zero.wav");
Schema.voices:Add("Combine", "1", "One.", "npc/combine_soldier/vo/one.wav");
Schema.voices:Add("Combine", "2", "Two.", "npc/combine_soldier/vo/two.wav");
Schema.voices:Add("Combine", "3", "Three.", "npc/combine_soldier/vo/three.wav");
Schema.voices:Add("Combine", "4", "Four.", "npc/combine_soldier/vo/four.wav");
Schema.voices:Add("Combine", "5", "Five.", "npc/combine_soldier/vo/five.wav");
Schema.voices:Add("Combine", "6", "Six.", "npc/combine_soldier/vo/six.wav");
Schema.voices:Add("Combine", "7", "Seven.", "npc/combine_soldier/vo/seven.wav");
Schema.voices:Add("Combine", "8", "Eight.", "npc/combine_soldier/vo/eight.wav");
Schema.voices:Add("Combine", "9", "Nine.", "npc/metropolice/vo/nine.wav");
Schema.voices:Add("Combine", "10", "Ten.", "npc/metropolice/vo/ten.wav");
Schema.voices:Add("Combine", "11", "Eleven.", "npc/metropolice/vo/eleven.wav");
Schema.voices:Add("Combine", "12", "Twelve.", "npc/metropolice/vo/twelve.wav");
Schema.voices:Add("Combine", "13", "Thirteen.", "npc/metropolice/vo/thirteen.wav");
Schema.voices:Add("Combine", "14", "Fourteen.", "npc/metropolice/vo/fourteen.wav");
Schema.voices:Add("Combine", "15", "Fifteen.", "npc/metropolice/vo/fifteen.wav");
Schema.voices:Add("Combine", "16", "Sixteen.", "npc/metropolice/vo/sixteen.wav");
Schema.voices:Add("Combine", "17", "Seventeen.", "npc/metropolice/vo/seventeen.wav");
Schema.voices:Add("Combine", "18", "Eighteen.", "npc/metropolice/vo/eighteen.wav");
Schema.voices:Add("Combine", "19", "Nineteen.", "npc/metropolice/vo/nineteen.wav");
Schema.voices:Add("Combine", "20", "Twenty.", "npc/metropolice/vo/twenty.wav");
Schema.voices:Add("Combine", "30", "Thirty.", "npc/metropolice/vo/thirty.wav");
Schema.voices:Add("Combine", "40", "Fourty.", "npc/metropolice/vo/fourty.wav");
Schema.voices:Add("Combine", "50", "Fifty.", "npc/metropolice/vo/fifty.wav");
Schema.voices:Add("Combine", "60", "Sixty.", "npc/metropolice/vo/sixty.wav");
Schema.voices:Add("Combine", "70", "Seventy.", "npc/metropolice/vo/seventy.wav");
Schema.voices:Add("Combine", "80", "Eighty.", "npc/metropolice/vo/eighty.wav");
Schema.voices:Add("Combine", "90", "Ninety.", "npc/metropolice/vo/ninety.wav");
Schema.voices:Add("Combine", "100", "One Hundred.", "npc/metropolice/vo/onehundred.wav");
Schema.voices:Add("Combine", "200", "Two Hundred", "npc/metropolice/vo/twohundred.wav");
Schema.voices:Add("Combine", "300", "Three Hundred", "npc/metropolice/vo/threehundred.wav");
Schema.voices:Add("Combine", "10-4", "10-4.", "npc/metropolice/vo/ten4.wav");
Schema.voices:Add("Combine", "10-2", "10-2.", "npc/metropolice/vo/ten2.wav");
Schema.voices:Add("Combine", "10-8", "Unit is on duty, 10-8.","npc/metropolice/vo/unitisonduty10-8.wav");
Schema.voices:Add("Combine", "10-8s", "10-8, standing by.", "npc/metropolice/vo/ten8standingby.wav");
Schema.voices:Add("Combine", "Is 10-8", "Unit is 10-8, standing by.", "npc/metropolice/vo/unitis10-8standingby.wav");
Schema.voices:Add("Combine", "10-14", "Holding on 10-14 duty at code 4.", "npc/metropolice/vo/holdingon10-14duty.wav");
Schema.voices:Add("Combine", "10-15", "Prepare for 10-15","npc/metropolice/vo/preparefor1015.wav");
Schema.voices:Add("Combine", "A 10-30", "I have a 10-30 at my 10-20, responding code 2.", "npc/metropolice/vo/ihave10-30my10-20responding.wav");
Schema.voices:Add("Combine", "11-44", "Get that 11-44 inbound, we're cleaning up now.", "npc/metropolice/vo/get11-44inboundcleaningup.wav");
Schema.voices:Add("Combine", "10-65", "Unit is 10-65.", "npc/metropolice/vo/ten97.wav");
Schema.voices:Add("Combine", "10-91", "10-91d count is..", "npc/metropolice/vo/ten91dcountis.wav");
Schema.voices:Add("Combine", "10-97 goa", "10-97, the suspect is GOA.", "npc/metropolice/vo/ten97suspectisgoa.wav");
Schema.voices:Add("Combine", "10-97", "10-97.", "npc/metropolice/vo/ten97.wav");
Schema.voices:Add("Combine", "10-99", "Officer down I am 10-99! Repeat I am 10-99!", "npc/metropolice/vo/officerdownIam10-99.wav");
Schema.voices:Add("Combine", "10-108", "We have a 10-108!","npc/metropolice/vo/wehavea10-108.wav");
Schema.voices:Add("Combine", "10-30", "I have a 10-30, my 10-20, responding code 2.", "npc/metropolice/vo/Ihave10-30my10-20responding.wav");
Schema.voices:Add("Combine", "10-107 here", "I have a 10-107 here, send Airwatch for tag.", "npc/metropolice/vo/gota10-107sendairwatch.wav");
Schema.voices:Add("Combine", "148", "148. Resisting arrest.", "npc/overwatch/radiovoice/resistingpacification148.wav");
Schema.voices:Add("Combine", "408", "I've got a 408 here at location.", "npc/metropolice/vo/Ivegot408hereatlocation.wav");
Schema.voices:Add("Combine", "95", "95, illegal carrying.", "npc/overwatch/radiovoice/illegalcarrying95.wav");
Schema.voices:Add("Combine", "69", "69, posession of resources.", "npc/overwatch/radiovoice/posession69.wav");
Schema.voices:Add("Combine", "603", "603, unlawful entry.", "npc/overwatch/radiovoice/unlawfulentry603.wav");
Schema.voices:Add("Combine", "94weapon", "94, weapon.", "npc/overwatch/radiovoice/weapon94.wav");
Schema.voices:Add("Combine", "51b", "51b, threat to property.", "npc/overwatch/radiovoice/threattoproperty51b.wav");
Schema.voices:Add("Combine", "103", "10-103m, disturbance by mentally unfit.", "npc/overwatch/radiovoice/disturbancemental10-103m.wav");
Schema.voices:Add("Combine", "243", "243, assault on protection team.", "npc/overwatch/radiovoice/assault243.wav");
Schema.voices:Add("Combine", "243 suspect", "All units report status on 243 suspect.", "npc/overwatch/radiovoice/statuson243suspect.wav");
Schema.voices:Add("Combine", "27", "27, attempted crime.", "npc/overwatch/radiovoice/attemptedcrime27.wav");
Schema.voices:Add("Combine", "63", "63, criminal trespass.", "npc/overwatch/radiovoice/criminaltrespass63.wav");
Schema.voices:Add("Combine", "51", "51, non-sanctioned arson.", "npc/overwatch/radiovoice/nonsanctionedarson51.wav");
Schema.voices:Add("Combine", "99", "99, reckless operation.", "npc/overwatch/radiovoice/recklessoperation99.wav");
Schema.voices:Add("Combine", "507", "507, public non-compliance.", "npc/overwatch/radiovoice/publicnoncompliance507.wav");
Schema.voices:Add("Combine", "187", "Suspect is now 187.", "npc/overwatch/radiovoice/suspectisnow187.wav");
Schema.voices:Add("Combine", "Anti-citizen one", "Anti-citizen one.", "npc/combine_soldier/vo/anticitizenone.wav");
Schema.voices:Add("Combine", "Officer down code 3", "Officer down, request all units Code 3 to my 10-20!", "npc/metropolice/vo/officerdowncode3tomy10-20.wav");
Schema.voices:Add("Combine", "Overwatch Team Down Sector Not Control", "Overwatch team is down, sector is not controlled.", "npc/combine_soldier/vo/overwatchteamisdown.wav");
Schema.voices:Add("Combine", "Sundown", "Sundown.", "npc/combine_soldier/vo/sundown.wav");
Schema.voices:Add("Combine", "Code 7", "Code 7.", "npc/metropolice/vo/code7.wav");
Schema.voices:Add("Combine", "Malcompliant 10-107", "Malcompliant 10-107 at my 10-20, preparing to prosecute.", "npc/metropolice/vo/malcompliant10107my1020.wav");
Schema.voices:Add("Combine", "A grenade", "That's a grenade!", "npc/metropolice/vo/thatsagrenade.wav");
Schema.voices:Add("Combine", "Standing by", "Standing by.", "npc/combine_soldier/vo/standingby].wav");
Schema.voices:Add("Combine", "Moved now", "Suspect has moved now to..", "npc/metropolice/vo/suspecthasmovednowto.wav");
Schema.voices:Add("Combine", "Ready to go", "Is ready to go!", "npc/metropolice/vo/isreadytogo.wav");
Schema.voices:Add("Combine", "Bouncer", "Bouncer, bouncer!", "npc/combine_soldier/vo/bouncerbouncer.wav");
Schema.voices:Add("Combine", "Standard Check", "Uh, roger that, we'll run standard loyalty check procedure 243, my 10-22 intake station, over.", "npc/metropolice/vo/standardloyaltycheck.wav");
Schema.voices:Add("Combine", "Begin scanning", "10-0, begin scanning.", "npc/overwatch/radiovoice/beginscanning10-0.wav");
Schema.voices:Add("Combine", "Complete sentencing", "All protection team units, complete sentencing at will.", "npc/overwatch/radiovoice/completesentencingatwill.wav");
Schema.voices:Add("Combine", "Reinforcement teams", "Reinforcement teams code 3.", "npc/overwatch/radiovoice/reinforcementteamscode3.wav");
Schema.voices:Add("Combine", "Report status", "Local CP teams report status.", "npc/metropolice/vo/localcptreportstatus.wav");
Schema.voices:Add("Combine", "Closing", "Officer closing on suspect.", "npc/overwatch/radiovoice/officerclosingonsuspect.wav");
Schema.voices:Add("Combine", "Investigate and report", "Investigate and report.", "npc/overwatch/radiovoice/investigateandreport.wav");
Schema.voices:Add("Combine", "Amputation", "Immediate amputation.", "npc/overwatch/radiovoice/immediateamputation.wav");
Schema.voices:Add("Combine", "Forward pressure", "All units apply forward pressure.", "npc/overwatch/radiovoice/allunitsapplyforwardpressure.wav");
Schema.voices:Add("Combine", "BOL suspect", "All units BOL for 243 suspect.", "npc/overwatch/radiovoice/allunitsbolfor243suspect.wav");
Schema.voices:Add("Combine", "Respond", "Respond.", "npc/overwatch/radiovoice/respond.wav");
Schema.voices:Add("Combine", "Sterilization", "All units begin witness sterilization.", "npc/overwatch/radiovoice/allunitsbeginwhitnesssterilization.wav");
Schema.voices:Add("Combine", "Contain", "Remaining units contain.", "npc/overwatch/radiovoice/remainingunitscontain.wav");
Schema.voices:Add("Combine", "Report please", "Report please.", "npc/overwatch/radiovoice/reportplease.wav");
Schema.voices:Add("Combine", "Stabilization", "Socio-stabilization restored.", "npc/overwatch/radiovoice/sociostabilizationrestored.wav");
Schema.voices:Add("Combine", "Charged with", "Attention, you have been charged with:", "npc/overwatch/radiovoice/attentionyouhavebeenchargedwith.wav");
Schema.voices:Add("Combine", "Final sentencing", "Prepare for final sentencing.", "npc/overwatch/radiovoice/prepareforfinalsentencing.wav");
Schema.voices:Add("Combine", "Receive verdict", "Prepare to receive verdict.", "npc/overwatch/radiovoice/preparetoreceiveverdict.wav");
Schema.voices:Add("Combine", "Judged guilty", "You are judged guilty by Civil Protection teams.", "npc/overwatch/radiovoice/youarejudgedguilty.wav");
Schema.voices:Add("Combine", "Capital malcompliance", "Capital malcompliance.", "npc/overwatch/radiovoice/capitalmalcompliance.wav");
Schema.voices:Add("Combine", "Level 5", "Level 5 anti-civil activity.", "npc/overwatch/radiovoice/level5anticivilactivity.wav");
Schema.voices:Add("Combine", "Unrest", "Promoting communal unrest.", "npc/overwatch/radiovoice/promotingcommunalunrest.wav");
Schema.voices:Add("Combine", "Civic trust", "Violation of civic trust.", "npc/overwatch/radiovoice/violationofcivictrust.wav");
Schema.voices:Add("Combine", "In progress", "In progress.", "npc/overwatch/radiovoice/inprogress.wav");
Schema.voices:Add("Combine", "Loyalty check", "Oh, I have a failure to comply with loyalty check, tag is possible 10-103m.", "npc/metropolice/vo/loyaltycheckfailure.wav");
Schema.voices:Add("Combine", "Going", "Going to take a look!", "npc/metropolice/vo/goingtotakealook.wav");
Schema.voices:Add("Combine", "Any help", "Need any help with this one?", "npc/metropolice/vo/needanyhelpwiththisone.wav");
Schema.voices:Add("Combine", "Get in", "Get in.", "vo/trainyard/ba_getin.wav");
Schema.voices:Add("Combine", "Get in here", "Get in here.", "vo/trainyard/ba_inhere01.wav");
Schema.voices:Add("Combine", "Come citizen", "You, citizen, come with me.", "vo/trainyard/ba_youcomewith.wav");
Schema.voices:Add("Combine", "Go on", "Go on.", "vo/trainyard/ba_goon.wav");
Schema.voices:Add("Combine", "No im good", "No, I'm good.", "vo/trainyard/ba_noimgood.wav");
Schema.voices:Add("Combine", "Back up", "Back up.", "vo/trainyard/ba_backup.wav");
Schema.voices:Add("Combine", "I said move", "I said move!", "vo/trainyard/ba_move01.wav");
Schema.voices:Add("Combine", "Tag 10-91d", "Tag 10-91d.", "npc/metropolice/vo/tag10-91d.wav");
Schema.voices:Add("Combine", "Tag One Bug", "Tag One Bug", "npc/metropolice/vo/.wav");
Schema.voices:Add("Combine", "Tag One Necrotic", "Tag one necrotic.", "npc/metropolice/vo/tagonenecrotic.wav");
Schema.voices:Add("Combine", "Tag One Parasitic", "Tag one parasitic.", "npc/metropolice/vo/tagoneparasitic.wav");
Schema.voices:Add("Combine", "heis", "There he is!", "npc/metropolice/vo/thereheis.wav");
Schema.voices:Add("Combine", "Hunting", "10-0, 10-0, viscerator is hunting.", "npc/metropolice/vo/tenzerovisceratorishunting.wav");
Schema.voices:Add("Combine", "Responding", "Responding.", "npc/metropolice/vo/responding2.wav");
Schema.voices:Add("Combine", "Contact Suspect", "Contact with 243 suspect. My 10-20 is..", "npc/metropolice/vo/contactwith243suspect.wav");
Schema.voices:Add("Combine", "Roller", "Roller.", "npc/metropolice/vo/roller.wav");
Schema.voices:Add("Combine", "Line", "Line.", "npc/metropolice/vo/line.wav");
Schema.voices:Add("Combine", "Grenade", "Grenade!", "npc/metropolice/vo/grenade.wav");
Schema.voices:Add("Combine", "Hold", "Hold it.", "npc/metropolice/vo/holdit.wav");
Schema.voices:Add("Combine", "Position", "Protection team, hold this position.", "npc/metropolice/vo/holdthisposition.wav");
Schema.voices:Add("Combine", "Down", "Is down!", "npc/metropolice/vo/isdown.wav");
Schema.voices:Add("Combine", "Take down", "Take him down!", "npc/metropolice/takedown.wav");
Schema.voices:Add("Combine", "Sacrifice code 1", "All units sacrifice code 1 and maintain this CP.", "npc/metropolice/vo/sacrificecode1maintaincp.wav");
Schema.voices:Add("Combine", "Stick", "Stick.", "npc/metropolice/vo/stick.wav");
Schema.voices:Add("Combine", "Activate Central", "Overwatch activate central transport stabilization teams.", "npc/combine_soldier/vo/prison_soldier_activatecentral.wav");
Schema.voices:Add("Combine", "Boomers inbound", "Overwatch confirm status, boomers inbound, prepare for special supression and report.", "npc/combine_soldier/vo/prison_soldier_boomersinbound.wav");
Schema.voices:Add("Combine", "Striker", "Striker!", "npc/combine_soldier/vo/striker.wav");
Schema.voices:Add("Combine", "Ranger", "Ranger!", "npc/combine_soldier/vo/ranger.wav");
Schema.voices:Add("Combine", "On Visual", "Acquiring on visual.", "npc/metropolice/vo/acquiringonvisual.wav");
Schema.voices:Add("Combine", "Affirmative 2", "Affirmative.", "npc/metropolice/vo/affirmative2.wav");
Schema.voices:Add("Combine", "BOL", "All Units, BOL, We have Thirty Four's At...", "npc/metropolice/vo/allunitsbol34sat.wav");
Schema.voices:Add("Combine", "Code2", "All units, Code two.", "npc/metropolice/vo/allunitscode2.wav");
Schema.voices:Add("Combine", "Pickup 647e", "Anyone else pickup a 647-E reading?", "npc/metropolice/vo/anyonepickup647e.wav");
Schema.voices:Add("Combine", "Back me up", "Back me up, I'm out!", "npc/metropolice/vo/backmeupImout.wav");
Schema.voices:Add("Combine", "Break Cover", "Break his cover!", "npc/metropolice/vo/breakhiscover.wav");
Schema.voices:Add("Combine", "No 647", "Clear, no 647, no 10-107.", "npc/metropolice/vo/clearno647no10-107.wav");
Schema.voices:Add("Combine", "Dead Body", "DB Count is...", "npc/metropolice/vo/dbcountis.wav");
Schema.voices:Add("Combine", "Deserviced Area", "Deserviced Area.", "npc/metropolice/vo/deservicedarea.wav");
Schema.voices:Add("Combine", "Establish Perimiter", "CP We need to establish perimiter at...", "npc/metropolice/vo/cpweneedtoestablishperimiterat.wav");
Schema.voices:Add("Combine", "Check miscount", "Check for miscount.", "npc/metropolice/vo/checkformiscount.wav");
Schema.voices:Add("Combine", "Airwatch 243", "CP we need Airwatch to BOL for that 243.", "npc/metropolice/vo/cpbolforthat243.wav");
Schema.voices:Add("Combine", "Bugs loose", "We have bugs on the loose.", "npc/metropolice/vo/bugsontheloose.wav");
Schema.voices:Add("Combine", "Is Passive", "Is Passive.", "npc/metropolice/vo/ispassive.wav");
Schema.voices:Add("Combine", "Move along2.", "Move along.", "npc/metropolice/vo/movealong.wav");
Schema.voices:Add("Combine", "Move it 2", "Move it!", "npc/metropolice/vo/moveit.wav");
Schema.voices:Add("Combine", "Suspect 11-6", "Suspect 11-6 my 10-20 is..", "npc/metropolice/vo/suspect11-6my1020is.wav");
Schema.voices:Add("Combine", "Non Tagged viromes", "Non tagged viromes here.", "npc/metropolice/vo/nontaggedviromeshere.wav");
Schema.voices:Add("Combine", "Officer under fire", "Officer under fire, taking cover!", "npc/metropolice/vo/officerunderfiretakingcover.wav");
Schema.voices:Add("Combine", "Quick", "Quick!", "npc/metropolice/vo/quick.wav");
Schema.voices:Add("Combine", "Got him again", "Got him again. Suspect is 10-20 at..", "npc/metropolice/vo/gothimagainsuspect10-20at.wav");
Schema.voices:Add("Combine", "Accomplice", "I got one accomplice here.", "npc/metropolice/vo/gotoneaccomplicehere.wav");
Schema.voices:Add("Combine", "Code 100", "Code 100.","npc/metropolice/vo/code100.wav");
Schema.voices:Add("Combine", "Teamdown", "Overwatch team is down this sector is not controlled!","npc/combine_soldier/vo/overwatchteamisdown.wav");
Schema.voices:Add("Combine", "Reinforcement", "Overwatch request reinforcement.","npc/combine_soldier/vo/overwatchrequestreinforcement.wav");
Schema.voices:Add("Combine", "10-78", "Dispatch I need 10-78, officer in trouble!","npc/metropolice/vo/dispatchIneed10-78.wav");
Schema.voices:Add("Combine", "Close Suspect", "All Units! Close on Suspect!","npc/metropolice/vo/allunitscloseonsuspect.wav");
Schema.voices:Add("Combine", "Ready Weapons Hostiles", "Ready weapons, possible hostiles inbound.","npc/combine_soldier/vo/readyweaponshostilesinbound.wav");
Schema.voices:Add("Combine", "Ready Charges", "Ready charges!","npc/combine_soldier/vo/readycharges.wav");
Schema.voices:Add("Combine", "Sector Secured", "Sector is Secured, no viscon.","npc/combine_soldier/vo/sectorissecurenovison.wav");
Schema.voices:Add("Combine", "Confirmed", "Contact Confirmed, Prosecuting!","npc/combine_soldier/vo/contactconfirmprosecuting.wav");
Schema.voices:Add("Combine", "Stabilization", "Stabilization team holding in position.","npc/combine_soldier/vo/stabilizationteamholding.wav");
Schema.voices:Add("Combine", "Infestation", "We are in an infestation zone.","npc/combine_soldier/vo/weareinaninfestationzone.wav");
Schema.voices:Add("Combine", "Medical", "Request Medical!","npc/combine_soldier/vo/requestmedical.wav");
Schema.voices:Add("Combine", "Stable at", "We are socio-stable at this location.", "npc/metropolice/vo/wearesociostablethislocation.wav");
Schema.voices:Add("Combine", "DB Here", "Uhh...we got a DB here, cancel that 11-42.", "npc/metropolice/vo/wegotadbherecancel10-102.wav");
Schema.voices:Add("Combine", "Preparing", "Preparing to judge a 10-107, be advised.", "npc/metropolice/vo/preparingtojudge10-107.wav");
Schema.voices:Add("Combine", "Possible 647", "Possible 647e here, request Airwatch tag.", "npc/metropolice/vo/possible647erequestairwatch.wav");
Schema.voices:Add("Combine", "Possible 10-103", "Possible 10-103, my location, alert tag units.", "npc/metropolice/vo/possible10-103alerttagunits.wav");
Schema.voices:Add("Combine", "Position to", "Position to contain.", "npc/metropolice/vo/positiontocontain.wav");
Schema.voices:Add("Combine", "Outland Biotic", "I got an outland biotic in here.", "npc/metropolice/vo/outlandbioticinhere.wav");
Schema.voices:Add("Combine", "Stay alert", "Stay alert, report sight lines.","npc/combine_soldier/vo/stayalertreportsightlines.wav");
Schema.voices:Add("Combine", "Positions", "All units move to arrest positions.","npc/metropolice/vo/movetoarrestpositions.wav");
Schema.voices:Add("Combine", "Pacifying", "Pacifying!","npc/metropolice/vo/pacifying.wav");
Schema.voices:Add("Combine", "Prosecute Final", "Ready to prosecute malcompliant citizen final warning issued!","npc/metropolice/vo/readytoprosecutefinalwarning.wav");
Schema.voices:Add("Combine", "Clearcode100", "Clear and code 100.","npc/metropolice/vo/clearandcode100.wav");
Schema.voices:Add("Combine", "Still 647e", "Still getting a 647e from local surveillance.","npc/metropolice/vo/stillgetting647e.wav");
Schema.voices:Add("Combine", "Blip", "Catch that blip on the stabilization readout?","npc/metropolice/vo/catchthatbliponstabilization.wav");
Schema.voices:Add("Combine", "Ripcord", "Ripcord.","npc/combine_soldier/vo/ripcord.wav");
Schema.voices:Add("Combine", "Ripcord 2", "Ripcord, ripcord!","npc/combine_soldier/vo/ripcordripcord.wav");
Schema.voices:Add("Combine", "Condemned", "Condemned zone.", "npc/metropolice/vo/condemnedzone.wav");
Schema.voices:Add("Combine", "Confirm Priority", "Confirm priority 1 sighted.", "npc/metropolice/vo/confirmpriority1sighted.wav");
Schema.voices:Add("Combine", "Converging", "Converging.", "npc/metropolice/vo/converging.wav");
Schema.voices:Add("Combine", "CP Compromised", "CP is compromised. Re-establish!", "npc/metropolice/vo/cpiscompromised.wav");
Schema.voices:Add("Combine", "Overrun", "CP is overrun, we have no containment!", "npc/metropolice/vo/cpisoverrunwehavenocontainment.wav");
Schema.voices:Add("Combine", "CP report in", "CP requests all units..uh..location report in.", "npc/metropolice/vo/cprequestsallunitsreportin.wav");
Schema.voices:Add("Combine", "Designate", "Designate suspect as..", "npc/metropolice/vo/designatesuspectas.wav");
Schema.voices:Add("Combine", "Dismounting", "Dismounting hardpoint.", "npc/metropolice/vo/dismountinghardpoint.wav");
Schema.voices:Add("Combine", "Disp Report", "Disp reports, suspect incursion at location.", "npc/metropolice/vo/dispreportssuspectincursion.wav");
Schema.voices:Add("Combine", "Disp Updating", "Disp updating APB likeness.", "npc/metropolice/vo/dispupdatingapb.wav");
Schema.voices:Add("Combine", "Distribution", "Distribution block.", "npc/metropolice/vo/distributionblock.wav");
Schema.voices:Add("Combine", "Hardpoint Scanning", "Hardpoint scanning.", "npc/metropolice/vo/hardpointscanning.wav");
Schema.voices:Add("Combine", "Hes 148", "He's gone 148!", "npc/metropolice/vo/hesgone148.wav");
Schema.voices:Add("Combine", "Up there", "He's up there!", "npc/metropolice/vo/hesupthere.wav");
Schema.voices:Add("Combine", "Hiding last", "Hiding, last seen at range..", "npc/metropolice/vo/hidinglastseenatrange.wav");
Schema.voices:Add("Combine", "High Priority", "High priority region.", "npc/metropolice/vo/highpriorityregion.wav");
Schema.voices:Add("Combine", "Industrial", "Industrial zone.", "npc/metropolice/vo/industrialzone.wav");
Schema.voices:Add("Combine", "Infested", "Infested zone.", "npc/metropolice/vo/infestedzone.wav");
Schema.voices:Add("Combine", "In position at", "In position at hardpoint.", "npc/metropolice/vo/inpositionathardpoint.wav");
Schema.voices:Add("Combine", "In position 1", "In position on 1 ready.", "npc/metropolice/vo/inpositionononeready.wav");
Schema.voices:Add("Combine", "At hardpoint", "Is at hardpoint, ready to prosecute.", "npc/metropolice/vo/isathardpointreadytoprosecute.wav");
Schema.voices:Add("Combine", "Is closing", "Is closing on suspect!", "npc/metropolice/vo/isclosingonsuspect.wav");
Schema.voices:Add("Combine", "Proceed", "Proceed to designated checkpoints.", "npc/metropolice/vo/proceedtocheckpoints.wav");
Schema.voices:Add("Combine", "At location", "Protect teams at location, report in.", "npc/metropolice/vo/ptatlocationreport.wav");
Schema.voices:Add("Combine", "PT go again", "PT go again.", "npc/metropolice/vo/ptgoagain.wav");
Schema.voices:Add("Combine", "Failure to", "Failure to comply with the civil will.", "npc/overwatch/radiovoice/failuretocomply.wav");
Schema.voices:Add("Combine", "OffWorld", "Permanent off-world service assignment.", "npc/overwatch/radiovoice/permanentoffworld.wav");
Schema.voices:Add("Combine", "Visual", "Attention: Prepare visual download of anti-citizen one.", "npc/overwatch/radiovoice/preparevisualdownload.wav");
Schema.voices:Add("Combine", "100 credits", "Rank leader, reminder: 100 sterilized credits qualifies non-mechanical reproduction simulation.", "npc/overwatch/radiovoice/reminder100credits.wav");
Schema.voices:Add("Combine", "Replacement", "Reminder: Memory replacement is the first step towards rank privileges.", "npc/overwatch/radiovoice/remindermemoryreplacement.wav");
Schema.voices:Add("Combine", "Incursion", "Restricted incursion in progress.", "npc/overwatch/radiovoice/restrictedincursioninprogress.wav");
Schema.voices:Add("Combine", "Reward Notice", "Reward notice, protection team member: Your family cohesion is preserved.", "npc/overwatch/radiovoice/rewardnotice.wav");
Schema.voices:Add("Combine", "Suspend Negotiations", "Suspend negotiations.", "npc/overwatch/radiovoice/suspendnegotiations.wav");
Schema.voices:Add("Combine", "Are Charged", "You are charged with terminal violation 148, 243, 245.", "npc/overwatch/radiovoice/youarechargedwithterminal.wav");
Schema.voices:Add("Combine", "Report on", "Local protection team units, report on..", "npc/overwatch/radiovoice/reporton.wav");
Schema.voices:Add("Combine", "No viscon", "No viscon.", "npc/combine_soldier/vo/noviscon.wav");
Schema.voices:Add("Combine", "Contact", "Contact.", "npc/combine_soldier/vo/contact.wav");
Schema.voices:Add("Combine", "Contact confirmed", "Contact confirmed, prosecuting.", "npc/combine_soldier/vo/contactconfirmprosecuting.wav");
Schema.voices:Add("Combine", "Team deployed", "Team is deployed and scanning.", "npc/combine_soldier/vo/teamdeployedandscanning.wav");
Schema.voices:Add("Combine", "Code3", "Reinforcement teams, code 3!", "npc/metropolice/vo/reinforcementteamscode3.wav");
Schema.voices:Add("Combine", "Report Sights", "Report sightings of possible accomplice.", "npc/metropolice/vo/reportsightingsaccomplices.wav");
Schema.voices:Add("Combine", "Repurposed", "Repurposed area.", "npc/metropolice/vo/repurposedarea.wav");
Schema.voices:Add("Combine", "Low on", "Running low on veridcts, taking cover!", "npc/metropolice/vo/runninglowonverdicts.wav");
Schema.voices:Add("Combine", "Shots fired", "Shots fired, hostile malignants here.", "npc/metropolice/vo/shotsfiredhostilemalignants.wav");
Schema.voices:Add("Combine", "Jurisdiction", "Stabilization jurisdiction.", "npc/metropolice/vo/stabilizationjurisdiction.wav");
Schema.voices:Add("Combine", "High speed", "All units be advised, subject is now high speed.", "npc/metropolice/vo/subjectisnowhighspeed.wav");
Schema.voices:Add("Combine", "UTL", "UTL suspect.", "npc/metropolice/vo/utlsuspect.wav");
Schema.voices:Add("Combine", "UTL that", "UTL that suspect.", "npc/metropolice/vo/utlthatsuspect.wav");
Schema.voices:Add("Combine", "Non Patrol", "Non patrol region.", "npc/metropolice/vo/nonpatrolregion.wav");
Schema.voices:Add("Combine", "Non-citizen", "Non-citizen.", "npc/metropolice/vo/noncitizen.wav");
Schema.voices:Add("Combine", "No contact", "No contact.", "npc/metropolice/vo/nocontact.wav");
Schema.voices:Add("Combine", "Hardpoint 2", "Moving to hardpoint!", "npc/metropolice/vo/movingtohardpoint2.wav");
Schema.voices:Add("Combine", "Match on", "I have a match on APB likeness.", "npc/metropolice/vo/matchonapblikeness.wav");
Schema.voices:Add("Combine", "Hiding Range", "Hiding, last seen at range..", "npc/metropolice/vo/hidinglastseenatrange.wav");
Schema.voices:Add("Combine", "Firing ", "Firing to expose target!", "npc/metropolice/vo/firingtoexposetarget.wav");
Schema.voices:Add("Combine", "Unit deserviced", "Unit deserviced.", "npc/overwatch/radiovoice/unitdeserviced.wav");
Schema.voices:Add("Combine", "Down at", "Unit down at..", "npc/overwatch/radiovoice/unitdownat.wav");
Schema.voices:Add("Combine", "Verdict is", "Suspect is judged malignant. Verdict code is..", "npc/overwatch/radiovoice/suspectmalignantverdictcodeis.wav");
Schema.voices:Add("Combine", "Fracture", "Social fracture in progress. Respond.", "npc/overwatch/radiovoice/socialfractureinprogress.wav");
Schema.voices:Add("Combine", "Recalibrate", "Team, recalibrate socio-scan.", "npc/overwatch/radiovoice/recalibratesocioscan.wav");
Schema.voices:Add("Combine", "Premature", "Premature mission termination will result in..", "npc/overwatch/radiovoice/prematuremissiontermination.wav");
Schema.voices:Add("Combine", "Lock down", "Protection team, lock down your location. Sacrifice code..", "npc/overwatch/radiovoice/lockdownlocationsacrificecode.wav");
Schema.voices:Add("Combine", "Leaders", "Attention stabilization team leaders: Report deserviced units to sterilized body count ratios for reinforcement reward or removal processing.", "npc/overwatch/radiovoice/leadersreportratios.wav");
Schema.voices:Add("Combine", "Reproduction", "50% reproduction credits.", "npc/overwatch/radiovoice/halfreproductioncredits.wav");
Schema.voices:Add("Combine", "Treat", "Stabilization team: Failure to treat identified local outbreak will foreseen recall and recycle.", "npc/overwatch/radiovoice/failuretotreatoutbreak.wav");
Schema.voices:Add("Combine", "Populcate", "Disassociation from the civic populace.", "npc/overwatch/radiovoice/disassociationfromcivic.wav");
Schema.voices:Add("Combine", "Destruction", "Destruction of corporal social protection units.", "npc/overwatch/radiovoice/destructionofcpt.wav");
Schema.voices:Add("Combine", "Verdict code is", "All units: Verdict code is..", "npc/overwatch/radiovoice/allunitsverdictcodeis.wav");
Schema.voices:Add("Combine", "Terminal", "All units deliver terminal verdict immediately.", "npc/overwatch/radiovoice/allunitsdeliverterminalverdict.wav");
Schema.voices:Add("Combine", "All Teams Code 3", "All teams respond code 3.", "npc/overwatch/radiovoice/allteamsrespondcode3.wav");
Schema.voices:Add("Combine", "Possible miscount", "Airwatch reports possible miscount.", "npc/overwatch/radiovoice/airwatchreportspossiblemiscount.wav");
Schema.voices:Add("Combine", "No activity", "Airwatch copies no activity.", "npc/overwatch/radiovoice/airwatchcopiesnoactivity.wav");
Schema.voices:Add("Combine", "Accomplices", "Protection team, be advised: Accomplices operating in area.", "npc/overwatch/radiovoice/accomplicesoperating.wav");
Schema.voices:Add("Combine", "Target", "Target.", "npc/combine_soldier/vo/target.wav");
Schema.voices:Add("Combine", "Target Compromised", "Target compromised, move in, move in!", "npc/combine_soldier/vo/targetcompromisedmovein.wav");
Schema.voices:Add("Combine", "Target Contact At", "Target contact at...", "npc/combine_soldier/vo/targetcontactat.wav");
Schema.voices:Add("Combine", "Target Contained", "Overwatch, target contained.", "npc/combine_soldier/vo/overwatchtargetcontained.wav");
Schema.voices:Add("Combine", "Target Ineffective", "Target ineffective!", "npc/combine_soldier/vo/targetineffective.wav");
Schema.voices:Add("Combine", "Target My Radial", "Target my radial.", "npc/combine_soldier/vo/targetmyradial.wav");
Schema.voices:Add("Combine", "Target One", "Target one.", "npc/combine_soldier/vo/targetone.wav");
Schema.voices:Add("Combine", "Target One Sterilized", "Overwatch target one sterilized.", "npc/combine_soldier/vo/overwatchtarget1sterilized.wav");
Schema.voices:Add("Combine", "Chatter1", "*Indistinct radio chatter*", "npc/combine_soldier/vo/prison_soldier_bunker1.wav");
Schema.voices:Add("Combine", "Chatter2", "*Indistinct radio chatter*", "npc/combine_soldier/vo/prison_soldier_bunker2.wav");
Schema.voices:Add("Combine", "Chatter3", "*Indistinct radio chatter*", "npc/combine_soldier/vo/prison_soldier_bunker3.wav");
Schema.voices:Add("Combine", "Chatter4", "*Indistinct radio chatter*", "npc/combine_soldier/vo/prison_soldier_containD8.wav");
Schema.voices:Add("Combine", "Chatter5", "*Indistinct radio chatter*", "npc/combine_soldier/vo/prison_soldier_fallback_b4.wav");
Schema.voices:Add("Combine", "Chatter6", "*Indistinct radio chatter*", "npc/combine_soldier/vo/prison_soldier_leader9dead.wav");
Schema.voices:Add("Combine", "Chatter7", "*Indistinct radio chatter*", "npc/combine_soldier/vo/prison_soldier_negativecontainment.wav");
Schema.voices:Add("Combine", "Chatter8", "*Indistinct radio chatter*", "npc/combine_soldier/vo/prison_soldier_prosecuteD7");
Schema.voices:Add("Combine", "Chatter9", "*Indistinct radio chatter*", "npc/combine_soldier/vo/prison_soldier_sundown3dead.wav");
Schema.voices:Add("Combine", "Chatter10", "*Indistinct radio chatter*", "npc/combine_soldier/vo/prison_soldier_tohighpoints.wav");
Schema.voices:Add("Combine", "Chatter11", "*Indistinct radio chatter*", "npc/combine_soldier/vo/prison_soldier_visceratorsA5.wav");
Schema.voices:Add("Combine", "Chatter12", "*Indistinct radio chatter*", "npc/combine_soldier/vo/prison_soldier_fullbioticoverrun.wav");
Schema.voices:Add("Combine", "Chatter13", "*Indistinct radio chatter*", "npc/combine_soldier/vo/prison_soldier_freeman_antlions.wav");
Schema.voices:Add("Combine", "HeadsUp", "Heads up!", "npc/metropolice/deploy01.wav");
Schema.voices:Add("Combine", "Let Em Loose", "Let 'em loose!", "npc/metropolice/deploy02.wav");
Schema.voices:Add("Combine", "Give Chase", "Give chase.", "npc/metropolice/deploy03.wav");
Schema.voices:Add("Combine", "Heads", "Heads!", "npc/metropolice/deploy04.wav");
Schema.voices:Add("Combine", "Deploying Remote", "Deploying remote!", "npc/metropolice/deploy05.wav");
Schema.voices:Add("Combine", "Release", "Release!", "npc/metropolice/deploy06.wav");
Schema.voices:Add("Combine", "Drop Weapon", "Drop your weapon, get down!", "npc/metropolice/dropweapon.wav");
Schema.voices:Add("Combine", "Freeze", "Freeze!", "npc/metropolice/freeze.wav");
Schema.voices:Add("Combine", "Get On Ground", "Stay where you are, get on the ground! Do it now!", "npc/metropolice/getonground.wav");
Schema.voices:Add("Combine", "Get Out There", "Get out of there!", "npc/metropolice/hiding01.wav");
Schema.voices:Add("Combine", "No Point Hiding", "There's no point in hiding.", "npc/metropolice/hiding02.wav");
Schema.voices:Add("Combine", "No Change Escape", "You have no chance of escape.", "npc/metropolice/hiding03.wav");
Schema.voices:Add("Combine", "You Are Surrounded", "You're surrounded.", "npc/metropolice/hiding04.wav");
Schema.voices:Add("Combine", "We Covered", "We have you covered.", "npc/metropolice/hiding05.wav");
Schema.voices:Add("Combine", "Over There1", "Over there!", "npc/metropolice/pointer01.wav");
Schema.voices:Add("Combine", "There1", "There!", "npc/metropolice/pointer02.wav");
Schema.voices:Add("Combine", "Look1", "Look!", "npc/metropolice/pointer03.wav");
Schema.voices:Add("Combine", "Dont Let Him Get Away", "Don't let him get away!", "npc/metropolice/pointer04.wav");
Schema.voices:Add("Combine", "There2", "There!", "npc/metropolice/pointer05.wav");
Schema.voices:Add("Combine", "Hes Getting Away", "He's getting away!", "npc/metropolice/pointer06.wav");
Schema.voices:Add("Combine", "Got Him", "Got him!", "npc/metropolice/shooter01.wav");
Schema.voices:Add("Combine", "Have Him", "I have him!", "npc/metropolice/shooter02.wav");
Schema.voices:Add("Combine", "Hes Mine", "He's mine!", "npc/metropolice/shooter03.wav");
Schema.voices:Add("Combine", "Right1", "Right.", "npc/metropolice/shooter04.wav");
Schema.voices:Add("Combine", "Yes See Him", "Yes, I see him.", "npc/metropolice/shooter05.wav");
Schema.voices:Add("Combine", "Surprise1", "What the?", "npc/metropolice/surprise1.wav");
Schema.voices:Add("Combine", "Surprise2", "Huh?", "npc/metropolice/surprise2.wav");
Schema.voices:Add("Combine", "Surprise3", "What the?", "npc/metropolice/surprise3.wav");
Schema.voices:Add("Combine", "Surprise4", "What the hell?", "npc/metropolice/surprise4.wav");
Schema.voices:Add("Combine", "Hes In Water", "He's in the water.", "npc/metropolice/water01.wav");
Schema.voices:Add("Combine", "Hold Back remotes", "Hold back the remotes.", "npc/metropolice/water02.wav");
Schema.voices:Add("Combine", "Hes Gone Below", "He's gone below!", "npc/metropolice/water03.wav");
Schema.voices:Add("Combine", "Belive What You Want", "Believe what you want.", "npc/metropolice/mc1ans_believewhatyouwant.wav");
Schema.voices:Add("Combine", "Quit Your Bellyachin", "Quit your bellyaching.", "npc/metropolice/mc1ans_bellyaching.wav");
Schema.voices:Add("Combine", "Could Be", "Eh, could be.", "npc/metropolice/mc1ans_couldbe.wav");
Schema.voices:Add("Combine", "Dont Be Ridiculous", "Don't be ridiculous.", "npc/metropolice/mc1ans_dontberidic.wav");
Schema.voices:Add("Combine", "Dont Wanna Talk", "I don't wanna talk about it.", "npc/metropolice/mc1ans_dontwannatalk.wav");
Schema.voices:Add("Combine", "Enough Outta You", "That's enough outta you.", "npc/metropolice/mc1ans_enoughouttayou.wav");
Schema.voices:Add("Combine", "Fascinating", "Fascinating.", "npc/metropolice/mc1ans_fascinating.wav");
Schema.voices:Add("Combine", "Figures", "Figures.", "npc/metropolice/mc1ans_figures.wav");
Schema.voices:Add("Combine", "Had To Partner", "I had to get you for a partner.", "npc/metropolice/mc1ans_hadtopartner.wav");
Schema.voices:Add("Combine", "Helluva Mood", "You're in helluva a mood.", "npc/metropolice/mc1ans_helluvamood.wav");
Schema.voices:Add("Combine", "Hm", "Hm.", "npc/metropolice/mc1ans_hm.wav");
Schema.voices:Add("Combine", "Huh Figures", "Huh, figures.", "npc/metropolice/mc1ans_huhfigures.wav");
Schema.voices:Add("Combine", "Let Me Think About", "Let me think about that.", "npc/metropolice/mc1ans_letmethink.wav");
Schema.voices:Add("Combine", "Might Be", "Might be.", "npc/metropolice/mc1ans_mightbe.wav");
Schema.voices:Add("Combine", "Might Could", "Might could.", "npc/metropolice/mc1ans_mightcould.wav");
Schema.voices:Add("Combine", "Might Not", "Might not.", "npc/metropolice/mc1ans_mightnot.wav");
Schema.voices:Add("Combine", "Nope", "Nope.", "npc/metropolice/mc1ans_nope.wav");
Schema.voices:Add("Combine", "Rather Not Talk", "I'd rather not talk about that.", "npc/metropolice/mc1ans_rathernottalk.wav");
Schema.voices:Add("Combine", "Rather Not Think About", "I'd rather not think about that.", "npc/metropolice/mc1ans_rathernotthink.wav");
Schema.voices:Add("Combine", "Shut Up About", "Shut up about that.", "npc/metropolice/mc1ans_shutup.wav");
Schema.voices:Add("Combine", "Stop Whining", "Stop whining.", "npc/metropolice/mc1ans_stopwhining.wav");
Schema.voices:Add("Combine", "Theres Your Problem", "There's your problem right there.", "npc/metropolice/mc1ans_theresyerproblem.wav");
Schema.voices:Add("Combine", "Think So", "Think so.", "npc/metropolice/mc1ans_thinkso.wav");
Schema.voices:Add("Combine", "Watch Your Mouth", "Watch your mouth.", "npc/metropolice/mc1ans_watchyermouth.wav");
Schema.voices:Add("Combine", "Yeah", "Yeah.", "npc/metropolice/mc1ans_yeah.wav");
Schema.voices:Add("Combine", "Yep", "Yep.", "npc/metropolice/mc1ans_yep.wav");
Schema.voices:Add("Combine", "You Expect Me To Belive", "You expect me to believe that?", "npc/metropolice/mc1ans_youexpectme.wav");
Schema.voices:Add("Combine", "You Really Belive", "You really believe that?", "npc/metropolice/mc1ans_youreallybelieve.wav");
Schema.voices:Add("Combine", "Got Better Things", "I got better things to do.", "npc/metropolice/mc1que_betterthings.wav");
Schema.voices:Add("Combine", "Best Career Choice", "Yep, this was definitely the best career choice I've ever made.", "npc/metropolice/mc1que_career.wav");
Schema.voices:Add("Combine", "Thinking About Enlisting", "So, I'm thinking about enlisting.", "npc/metropolice/mc1que_enlisting.wav");
Schema.voices:Add("Combine", "Everything I Hoped", "This is everything I hoped it would be.", "npc/metropolice/mc1que_everythingihoped.wav");
Schema.voices:Add("Combine", "Feeling Good", "I'm feeling pretty good about myself today.", "npc/metropolice/mc1que_feelinggood.wav");
Schema.voices:Add("Combine", "Feet Killing", "My feet are killing me.", "npc/metropolice/mc1que_feetkillin.wav");
Schema.voices:Add("Combine", "Place Going To Hell", "This whole place is going to hell. Well, not this place.", "npc/metropolice/mc1que_goingtohell.wav");
Schema.voices:Add("Combine", "Just Thought Something", "I just thought of something. Uh, wait... Maybe not.", "npc/metropolice/mc1que_justthought.wav");
Schema.voices:Add("Combine", "Wouldnt Have Kids", "I wouldn't have kids even if they let me.", "npc/metropolice/mc1que_kids.wav");
Schema.voices:Add("Combine", "Beats Last Job", "Beats the shit out of my last job.", "npc/metropolice/mc1que_lastjob.wav");
Schema.voices:Add("Combine", "Get Pay Cut", "What do you bet we get a pay cut?", "npc/metropolice/mc1que_paycut.wav");
Schema.voices:Add("Combine", "People Suck Except Us", "People suck. Well, except for us.", "npc/metropolice/mc1que_peoplesuck.wav");
Schema.voices:Add("Combine", "Getting Perks", "So, you getting the perks they promised you?", "npc/metropolice/mc1que_perks.wav");
Schema.voices:Add("Combine", "Raise Next Week", "Supposedly we're getting a raise next week.", "npc/metropolice/mc1que_raise.wav");
Schema.voices:Add("Combine", "Use Another Stimpatch", "I could use another stimpatch.", "npc/metropolice/mc1que_stimpatch.wav");
Schema.voices:Add("Combine", "Stomach Killing", "My stomach is killing me.", "npc/metropolice/mc1que_stomach.wav");
Schema.voices:Add("Combine", "Getting New Stunsticks", "I heard we're not getting those new stun sticks this year.", "npc/metropolice/mc1que_stunsticks.wav");
Schema.voices:Add("Combine", "This Is Ridiculous", "This is ridiculous.", "npc/metropolice/mc1que_thisridiculous.wav");
Schema.voices:Add("Combine", "Your Wife Doesnt Like Me", "Your wife doesn't like me, does she?", "npc/metropolice/mc1que_yourwife.wav");
Schema.voices:Add("Combine", "Belive What You Want2", "Believe what you want.", "npc/metropolice/mc2ans_believewhatyouwant.wav");
Schema.voices:Add("Combine", "Quit Your Bellyaching2", "Quit your bellyaching.", "npc/metropolice/mc2ans_bellyaching.wav");
Schema.voices:Add("Combine", "Could Be2", "Eh, could be.", "npc/metropolice/mc2ans_couldbe.wav");
Schema.voices:Add("Combine", "Dont Be Ridiculous2", "Don't be ridiculous.", "npc/metropolice/mc2ans_dontridiculous.wav");
Schema.voices:Add("Combine", "Dont Wanna Talk2", "I don't want to talk about it.", "npc/metropolice/mc2ans_dontwannatalk.wav");
Schema.voices:Add("Combine", "Dont Want Talk", "I don't want to talk about it.", "npc/metropolice/mc2ans_dontwannatalk2.wav");
Schema.voices:Add("Combine", "Enough Outta You2", "That's enough outta you.", "npc/metropolice/mc2ans_enoughouttayou.wav");
Schema.voices:Add("Combine", "Fascinating2", "Fascinating.", "npc/metropolice/mc2ans_fascinating.wav");
Schema.voices:Add("Combine", "Figures2", "Figures.", "npc/metropolice/mc2ans_figures.wav");
Schema.voices:Add("Combine", "Helluva Mood2", "You're in helluva a mood.", "npc/metropolice/mc2ans_helluvamood.wav");
Schema.voices:Add("Combine", "Let Me Think About2", "Let me think about that.", "npc/metropolice/mc2ans_lemmethink.wav");
Schema.voices:Add("Combine", "Might Be2", "Might be.", "npc/metropolice/mc2ans_mightbe.wav");
Schema.voices:Add("Combine", "Might Could2", "Might could.", "npc/metropolice/mc2ans_mightcould.wav");
Schema.voices:Add("Combine", "Might Not2", "Might not.", "npc/metropolice/mc2ans_mightnot.wav");
Schema.voices:Add("Combine", "Nope2", "Nope.", "npc/metropolice/mc2ans_nope.wav");
Schema.voices:Add("Combine", "Nope3", "Nope.", "npc/metropolice/mc2ans_nope2.wav");
Schema.voices:Add("Combine", "Rather Not Think About2", "I'd rather not think about that.", "npc/metropolice/mc2ans_rathernotthink.wav");
Schema.voices:Add("Combine", "Shut Up About2", "Shut up about that.", "npc/metropolice/mc2ans_shutup.wav");
Schema.voices:Add("Combine", "Stop Whining2", "Stop whining.", "npc/metropolice/mc2ans_stopwhining.wav");
Schema.voices:Add("Combine", "Stop Whining3", "Stop whining.", "npc/metropolice/mc2ans_stopwhining2.wav");
Schema.voices:Add("Combine", "Theres Your Problem1", "There's your problem right there.", "npc/metropolice/mc2ans_theresyerproblem.wav");
Schema.voices:Add("Combine", "Theres Your Problem2", "There's your problem right there.", "npc/metropolice/mc2ans_theresyerproblem2.wav");
Schema.voices:Add("Combine", "Think So2", "Think so.", "npc/metropolice/mc2ans_thinkso.wav");
Schema.voices:Add("Combine", "Watch Your Mouth2", "Watch your mouth.", "npc/metropolice/mc2ans_watchmouth.wav");
Schema.voices:Add("Combine", "Yeah2", "Yeah.", "npc/metropolice/mc2ans_yeah.wav");
Schema.voices:Add("Combine", "Yep2", "Yep.", "npc/metropolice/mc2ans_yep.wav");
Schema.voices:Add("Combine", "You Expect Me To Belive2", "You expect me to believe that?", "npc/metropolice/mc2ans_youexpectme.wav");
Schema.voices:Add("Combine", "Had To Partner2", "I had to get you for a partner.", "npc/metropolice/mc2ans_youforpartner.wav");
Schema.voices:Add("Combine", "You Really Belive2", "You really believe that?", "npc/metropolice/mc2ans_youreallybelieve.wav");
Schema.voices:Add("Combine", "You Really Belive3", "You really believe that?", "npc/metropolice/mc2ans_youreallybelieve2.wav");
Schema.voices:Add("Combine", "Yup", "Yup.", "npc/metropolice/mc2ans_yup.wav");
Schema.voices:Add("Combine", "Yup2", "Yup.", "npc/metropolice/mc2ans_yup2.wav");
Schema.voices:Add("Combine", "Got Better Things2", "I got better things to do.", "npc/metropolice/mc2que_betterthings.wav");
Schema.voices:Add("Combine", "Best Career Choice2", "Yep, this was definitely the best career choice I've ever made.", "npc/metropolice/mc2que_career.wav");
Schema.voices:Add("Combine", "Thinking About Enlisting2", "So, I'm thinking about enlisting.", "npc/metropolice/mc2que_enlisting.wav");
Schema.voices:Add("Combine", "Everything I Hoped2", "This is everything I hoped it would be.", "npc/metropolice/mc2que_everythingihoped.wav");
Schema.voices:Add("Combine", "Feeling Good2", "I'm feeling pretty good about myself today.", "npc/metropolice/mc2que_feelinggood.wav");
Schema.voices:Add("Combine", "Feet Killing2", "My feet are killing me.", "npc/metropolice/mc1que_feetkilling.wav");
Schema.voices:Add("Combine", "Feet Killing3", "My feet are killing me.", "npc/metropolice/mc1que_feetkilling2.wav");
Schema.voices:Add("Combine", "Place Going To Hell3", "This whole place is going to hell. No. Not this place.", "npc/metropolice/mc2que_goingtohell.wav");
Schema.voices:Add("Combine", "Place Going To Hell2", "This whole place is going to hell. Well, not this place.", "npc/metropolice/mc2que_goingtohell2.wav");
Schema.voices:Add("Combine", "Just Thought Something2", "I just thought of something. Uh, wait... Maybe not.", "npc/metropolice/mc2que_justthought.wav");
Schema.voices:Add("Combine", "Just Thought Something3", "I just thought of something. Uh, wait... Maybe not.", "npc/metropolice/mc2que_justthought2.wav");
Schema.voices:Add("Combine", "Wouldnt Have Kids2", "I wouldn't have kids even if they let me.", "npc/metropolice/mc2que_kids.wav");
Schema.voices:Add("Combine", "Beats Last Job2", "Beats the shit out of my last job.", "npc/metropolice/mc2que_lastjob.wav");
Schema.voices:Add("Combine", "Get Pay Cut2", "What do you bet we get a pay cut?", "npc/metropolice/mc2que_paycut.wav");
Schema.voices:Add("Combine", "People Suck Except Us2", "People suck. Well, except for us.", "npc/metropolice/mc2que_peoplesuck.wav");
Schema.voices:Add("Combine", "Getting Perks2", "So, you getting the perks they promised you?", "npc/metropolice/mc2que_perks.wav");
Schema.voices:Add("Combine", "Raise Next Week2", "Supposedly we're getting a raise next week.", "npc/metropolice/mc2que_raise.wav");
Schema.voices:Add("Combine", "Use Another Stimpatch2", "I could use another stimpatch.", "npc/metropolice/mc2que_stimpatch.wav");
Schema.voices:Add("Combine", "Stomach Killing2", "My stomach is killing me.", "npc/metropolice/mc2que_stomach.wav");
Schema.voices:Add("Combine", "Stomach Killing3", "My stomach is killing me.", "npc/metropolice/mc2que_stomach2.wav");
Schema.voices:Add("Combine", "Getting New Stunsticks2", "I heard we're not getting those new stun sticks this year.", "npc/metropolice/mc2que_stunsticks.wav");
Schema.voices:Add("Combine", "Your Wife Doesnt Like Me2", "Your wife doesn't like me, does she?", "npc/metropolice/mc2que_yourwife.wav");
Schema.voices:Add("Combine", "Affirmative2", "Affirmative.", "npc/metropolice/vo/affirmative2.wav");
Schema.voices:Add("Combine", "Airwatch Subject Is 505", "Dispatch, we need airwatch, subject is 505.", "npc/metropolice/vo/airwatchsubjectis505.wav");
Schema.voices:Add("Combine", "All Units Maintain CP", "All units maintain this CP.", "npc/metropolice/vo/allunitsmaintainthiscp.wav");
Schema.voices:Add("Combine", "All Report Location Of Suspect", "All units report location of suspect.", "npc/metropolice/vo/allunitsreportlocationsuspect.wav");
Schema.voices:Add("Combine", "Assault Point Secure Advance", "Assault point secure. Advance.", "npc/metropolice/vo/assaultpointsecureadvance.wav");
Schema.voices:Add("Combine", "At Checkpoint", "At checkpoint.", "npc/metropolice/vo/atcheckpoint.wav");
Schema.voices:Add("Combine", "Block", "Block.", "npc/metropolice/vo/block.wav");
Schema.voices:Add("Combine", "Block Holding Cohesive", "Block is holding, cohesive.", "npc/metropolice/vo/blockisholdingcohesive.wav");
Schema.voices:Add("Combine", "Bugs", "Bugs.", "npc/metropolice/vo/bugs.wav");
Schema.voices:Add("Combine", "Canal", "Canal.", "npc/metropolice/vo/canal.wav");
Schema.voices:Add("Combine", "Canal Block", "Canal block.", "npc/metropolice/vo/canalblock.wav");
Schema.voices:Add("Combine", "Cauterize", "Cauterize.", "npc/metropolice/vo/cauterize.wav");
Schema.voices:Add("Combine", "Citizen Summoned", "Reporting citizen summoned to voluntary conscription for general service public detail T94-322.", "npc/metropolice/vo/citizensummoned.wav");
Schema.voices:Add("Combine", "Classify This Block Ready", "Classify subject name as DB this block ready for cleanout.", "npc/metropolice/vo/classifyasdbthisblockready.wav");
Schema.voices:Add("Combine", "Confirm ADW", "Confirmed ADW on that suspect. 10-0.", "npc/metropolice/vo/confirmadw.wav");
Schema.voices:Add("Combine", "Contact Priority 2", "Contact with a priority 2.", "npc/metropolice/vo/contactwithpriority2.wav");
Schema.voices:Add("Combine", "Control 100 Percent", "Control is 100 percent this location. No sign of that 647-E.", "npc/metropolice/vo/control100percent.wav");
Schema.voices:Add("Combine", "Control Section", "Control section.", "npc/metropolice/vo/controlsection.wav");
Schema.voices:Add("Combine", "CP Need Establish Perimeter At", "CP we need to establish a perimeter at.", "npc/metropolice/vo/cpweneedtoestablishaperimeterat.wav");
Schema.voices:Add("Combine", "Defender", "Defender!", "npc/metropolice/vo/defender.wav");
Schema.voices:Add("Combine", "Docoument", "Document.", "npc/metropolice/vo/document.wav");
Schema.voices:Add("Combine", "Establish New CP", "Fall out, establish a new CP.", "npc/metropolice/vo/establishnewcp.wav");
Schema.voices:Add("Combine", "Examine", "Examine.", "npc/metropolice/vo/examine.wav");
Schema.voices:Add("Combine", "Expired", "Expired.", "npc/metropolice/vo/expired.wav");
Schema.voices:Add("Combine", "External Jurisdiction", "External jurisdiction.", "npc/metropolice/vo/externaljurisdiction.wav");
Schema.voices:Add("Combine", "Fire To Dislocate Interpose", "Fire to dislocate that interpose!", "npc/metropolice/vo/firetodislocateinterpose.wav");
Schema.voices:Add("Combine", "Freeman", "Freeman.", "npc/metropolice/vo/freeman.wav");
Schema.voices:Add("Combine", "Free Necrotics", "I have free necrotics.", "npc/metropolice/vo/freenecrotics.wav");
Schema.voices:Add("Combine", "Hero", "Hero!", "npc/metropolice/vo/hero.wav");
Schema.voices:Add("Combine", "Infection", "Infection.", "npc/metropolice/vo/infection.wav");
Schema.voices:Add("Combine", "Innoculate", "Innoculate.", "npc/metropolice/vo/innoculate.wav");
Schema.voices:Add("Combine", "In Position", "In position.", "npc/metropolice/vo/inposition.wav");
Schema.voices:Add("Combine", "Intercede", "Intercede.", "npc/metropolice/vo/intercede.wav");
Schema.voices:Add("Combine", "Interlock", "Interlock.", "npc/metropolice/vo/interlock.wav");
Schema.voices:Add("Combine", "Investigate", "Investigate.", "npc/metropolice/vo/investigate.wav");
Schema.voices:Add("Combine", "Investigating 10-103", "Investigating 10-103.", "npc/metropolice/vo/investigating10-103.wav");
Schema.voices:Add("Combine", "Is 10-108", "Is 10-108!", "npc/metropolice/vo/is10-108.wav");
Schema.voices:Add("Combine", "Is 415-B", "Is 415-B.", "npc/metropolice/vo/is415b.wav");
Schema.voices:Add("Combine", "Is Go", "Is go.", "npc/metropolice/vo/isgo.wav");
Schema.voices:Add("Combine", "Is Moving In", "Is moving in.", "npc/metropolice/vo/ismovingin.wav");
Schema.voices:Add("Combine", "Level 3 Civil Privacy Violator", "I have a level 3 civil privacy violator here.", "npc/metropolice/vo/level3civilprivacyviolator.wav");
Schema.voices:Add("Combine", "Look Out Rouge Viscerator", "Look out, rogue viscerator!", "npc/metropolice/vo/lookoutrogueviscerator.wav");
Schema.voices:Add("Combine", "Loose Parasitics", "Loose parasitics!", "npc/metropolice/vo/looseparasitics.wav");
Schema.voices:Add("Combine", "Malignant", "Malignant.", "npc/metropolice/vo/malignant.wav");
Schema.voices:Add("Combine", "Meters", "Meters!", "npc/metropolice/vo/meters.wav");
Schema.voices:Add("Combine", "Moving To Cover", "Moving to cover!", "npc/metropolice/vo/movingtocover.wav");
Schema.voices:Add("Combine", "Non Tagged Viromes Here", "Non-tagged viromes here", "npc/metropolice/vo/non-taggedviromeshere.wav");
Schema.voices:Add("Combine", "No Visual UPI", "No visual on UPI at this time.", "npc/metropolice/vo/novisualonupi.wav");
Schema.voices:Add("Combine", "Outbreak2", "Outbreak.", "npc/metropolice/vo/outbreak.wav");
Schema.voices:Add("Combine", "Outlandzone", "Outland zone.", "npc/metropolice/vo/outlandzone.wav");
Schema.voices:Add("Combine", "Picking Up Non Corplex Indy", "Picking up a non corplex indy over here.", "npc/metropolice/vo/pickingupnoncorplexindy.wav");
Schema.voices:Add("Combine", "Production Block", "Production block.", "npc/metropolice/vo/productionblock.wav");
Schema.voices:Add("Combine", "Ready To Judge", "Ready to judge.", "npc/metropolice/vo/readytojudge.wav");
Schema.voices:Add("Combine", "Ready To Prosecute", "Ready to prosecute.", "npc/metropolice/vo/readytoprosecute.wav");
Schema.voices:Add("Combine", "Request Secondary Viscerator", "Request secondary viscerator, primary is in cap.", "npc/metropolice/vo/requestsecondaryviscerator.wav");
Schema.voices:Add("Combine", "Residential Block", "Residential Block.", "npc/metropolice/vo/residentialblock.wav");
Schema.voices:Add("Combine", "Searching For Suspect No Status", "Searching for suspect, no status.", "npc/metropolice/vo/searchingforsuspect.wav");
Schema.voices:Add("Combine", "Second Warning Given", "Second warning given.", "npc/metropolice/vo/secondwarning.wav");
Schema.voices:Add("Combine", "Sociocide", "Sociocide.", "npc/metropolice/vo/sociocide.wav");
Schema.voices:Add("Combine", "Station Block", "Station block.", "npc/metropolice/vo/stationblock.wav");
Schema.voices:Add("Combine", "Storm System", "Storm System.", "npc/metropolice/vo/stormsystem.wav");
Schema.voices:Add("Combine", "Subject", "Subject.", "npc/metropolice/vo/subject.wav");
Schema.voices:Add("Combine", "Subject Moved Now To", "Suspect has moved now to.", "npc/metropolice/vo/supsecthasmovednowto.wav");
Schema.voices:Add("Combine", "Suspect In Storm Runoff", "All units, suspect is in storm runoff system at.", "npc/metropolice/vo/suspectinstormrunoff.wav");
Schema.voices:Add("Combine", "Suspect Is Bleeding Multiple", "Suspect is bleeding from multiple wounds.", "npc/metropolice/vo/suspectisbleeding.wav");
Schema.voices:Add("Combine", "Suspend", "Suspend.", "npc/metropolice/vo/suspend.wav");
Schema.voices:Add("Combine", "Sweeping For Suspect", "Sweeping for suspect.", "npc/metropolice/vo/sweepingforsuspect.wav");
Schema.voices:Add("Combine", "Tag One Bug", "Tag one bug.", "npc/metropolice/vo/tagonebug.wav");
Schema.voices:Add("Combine", "Tap", "Tap.", "npc/metropolice/vo/tap.wav");
Schema.voices:Add("Combine", "Team In Position Advance", "Team in position, advance.", "npc/metropolice/vo/teaminpositionadvance.wav");
Schema.voices:Add("Combine", "There He Goes At", "There he goes, he's at.", "npc/metropolice/vo/therehegoeshesat.wav");
Schema.voices:Add("Combine", "Transit Block", "Transit block.", "npc/metropolice/vo/transitblock.wav");
Schema.voices:Add("Combine", "Is 10-65", "Unit is 10-65.", "npc/metropolice/vo/unitis10-65.wav");
Schema.voices:Add("Combine", "Report In With 10-25 Suspect", "Any unit, report in with 10-25 suspect.", "npc/metropolice/vo/unitreportinwith10-25suspect.wav");
Schema.voices:Add("Combine", "UPI", "UPI.", "npc/metropolice/vo/upi.wav");
Schema.voices:Add("Combine", "Viscerator Deployed", "Viscerator deployed.", "npc/metropolice/vo/visceratordeployed.wav");
Schema.voices:Add("Combine", "Viscerator OC", "Viscerator is OC!", "npc/metropolice/vo/visceratorisoc.wav");
Schema.voices:Add("Combine", "Viscerator Off Grid", "Viscerator is off grid", "npc/metropolice/vo/visceratorisoffgrid.wav");
Schema.voices:Add("Combine", "Waste River", "Waste river.", "npc/metropolice/vo/wasteriver.wav");
Schema.voices:Add("Combine", "Workforce Intake.", "Workforce intake.", "npc/metropolice/vo/workforceintake.wav");
Schema.voices:Add("Combine", "Yellow", "Yellow.", "npc/metropolice/vo/yellow.wav");
Schema.voices:Add("Combine", "Get Against Wall", "Get against the wall.", "vo/trainyard/ba_againstwall.wav");
Schema.voices:Add("Combine", "Get Away There", "Get away from there!", "vo/trainyard/ba_awayfrom.wav");
Schema.voices:Add("Combine", "Back Off", "Back off!", "vo/trainyard/ba_backoff.wav");
Schema.voices:Add("Combine", "Get Up There", "Get up there.", "vo/trainyard/ba_getupthere.wav");
Schema.voices:Add("Combine", "Go On Up", "Go on up.", "vo/trainyard/ba_goonup.wav");
Schema.voices:Add("Combine", "In Here", "In here, let's go.", "vo/trainyard/ba_inhere.wav");
Schema.voices:Add("Combine", "Keep Moving2", "Keep moving!", "vo/trainyard/ba_keepmoving.wav");
Schema.voices:Add("Combine", "Move2", "Move!", "vo/trainyard/ba_move.wav");
Schema.voices:Add("Combine", "Not In There", "Not in there.", "vo/trainyard/ba_notthere.wav");
Schema.voices:Add("Combine", "Out Of Way", "Out of the way!", "vo/trainyard/ba_outofway.wav");
Schema.voices:Add("Combine", "Over Here", "Over here", "vo/trainyard/ba_overhere.wav");
Schema.voices:Add("Combine", "Need Some Privacy", "Yeah. I'm gonna need some privacy for this.", "vo/trainyard/ba_privacy.wav");
Schema.voices:Add("Combine", "Thats It", "Yeah, that's it.", "vo/trainyard/ba_thatsit.wav");
Schema.voices:Add("Combine", "Get Up Here", "Get up here!", "vo/trainyard/ba_uphere.wav");
Schema.voices:Add("Combine", "Alert 1", "Alert 1.", "npc/combine_soldier/vo/alert1.wav");
Schema.voices:Add("Combine", "Bearing", "Bearing!", "npc/combine_soldier/vo/bearing.wav");
Schema.voices:Add("Combine", "Block 31 Mace", "Block 31 mace.", "npc/combine_soldier/vo/block31mace.wav");
Schema.voices:Add("Combine", "Block 64 Jet", "Block 64 jet.", "npc/combine_soldier/vo/block64jet.wav");
Schema.voices:Add("Combine", "Bodypack Holding", "Bodypack holding.", "npc/combine_soldier/vo/bodypackholding.wav");
Schema.voices:Add("Combine", "Boomer", "Boomer.", "npc/combine_soldier/vo/Boomer.wav");
Schema.voices:Add("Combine", "Call Contact Parasitics", "Call contact parasitics.", "npc/combine_soldier/vo/callcontactparasitics.wav");
Schema.voices:Add("Combine", "Call Contact Suspect Target 1", "Call contact suspect target 1.", "npc/combine_soldier/vo/callcontacttarget1.wav");
Schema.voices:Add("Combine", "Call Hot Point", "Call hot point.", "npc/combine_soldier/vo/callhotpoint.wav");
Schema.voices:Add("Combine", "Closing1", "Closing.", "npc/combine_soldier/vo/closing.wav");
Schema.voices:Add("Combine", "Closing2", "Closing.", "npc/combine_soldier/vo/closing2.wav");
Schema.voices:Add("Combine", "Confirm Sector Not Sterile", "Confirm sector not sterile.", "npc/combine_soldier/vo/confirmsectornotsterile.wav");
Schema.voices:Add("Combine", "Contact Confirm", "Contact confirm.", "npc/combine_soldier/vo/contactconfim.wav");
Schema.voices:Add("Combine", "Contained", "Contained.", "npc/combine_soldier/vo/contained.wav");
Schema.voices:Add("Combine", "Containment Proceeding", "Containment proceeding.", "npc/combine_soldier/vo/containmentproceeding.wav");
Schema.voices:Add("Combine", "Copy2", "Copy.", "npc/combine_soldier/vo/copy.wav");
Schema.voices:Add("Combine", "Cover", "Cover.", "npc/combine_soldier/vo/cover.wav");
Schema.voices:Add("Combine", "Cover2", "Cover!", "npc/combine_soldier/vo/coverhurt.wav");
Schema.voices:Add("Combine", "Cover Me 1", "Cover me.", "npc/combine_soldier/vo/coverme.wav");
Schema.voices:Add("Combine", "Degrees", "Degrees.", "npc/combine_soldier/vo/degrees.wav");
Schema.voices:Add("Combine", "Designate Target", "Designate target as.", "npc/combine_soldier/vo/designatetargetas.wav");
Schema.voices:Add("Combine", "Displace", "Displace.", "npc/combine_soldier/vo/displace.wav");
Schema.voices:Add("Combine", "Displace2", "Displace.", "npc/combine_soldier/vo/displace2.wav");
Schema.voices:Add("Combine", "Extractor Away", "Extractor away.", "npc/combine_soldier/vo/extractoraway.wav");
Schema.voices:Add("Combine", "Extractor Is Live", "Extractor is live.", "npc/combine_soldier/vo/extractorislive.wav");
Schema.voices:Add("Combine", "Fist", "Fist!", "npc/combine_soldier/vo/fist.wav");
Schema.voices:Add("Combine", "Fix Sight Lines Move In", "Fix sight lines, move in!", "npc/combine_soldier/vo/fixsightlinesmovein.wav");
Schema.voices:Add("Combine", "Flare Down", "Flare Down!", "npc/combine_soldier/vo/flaredown.wav");
Schema.voices:Add("Combine", "Flash", "Flash!", "npc/combine_soldier/vo/flash.wav");
Schema.voices:Add("Combine", "Flat Line", "Flat Line.", "npc/combine_soldier/vo/flatline.wav");
Schema.voices:Add("Combine", "Flush", "Flush!", "npc/combine_soldier/vo/flush.wav");
Schema.voices:Add("Combine", "Freeman", "Freeman!", "npc/combine_soldier/vo/freeman3.wav");
Schema.voices:Add("Combine", "Full Active", "Full Active.", "npc/combine_soldier/vo/fullactive.wav");
Schema.voices:Add("Combine", "Ghost Two", "Ghost Two!", "npc/combine_soldier/vo/ghost2.wav");
Schema.voices:Add("Combine", "Go Active Intercept", "Go active intercept.", "npc/combine_soldier/vo/goactiveintercept.wav");
Schema.voices:Add("Combine", "Go Sharp 1", "Go Sharp!", "npc/combine_soldier/vo/gosharp.wav");
Schema.voices:Add("Combine", "Grid Sundown 46", "Grid sundown 46.", "npc/combine_soldier/vo/gridsundown46.wav");
Schema.voices:Add("Combine", "Hammer", "Hammer!", "npc/combine_soldier/vo/hammer.wav");
Schema.voices:Add("Combine", "Has Negative Movement", "Has negative movement.", "npc/combine_soldier/vo/hasnegativemovement.wav");
Schema.voices:Add("Combine", "Hunter", "Hunter!", "npc/combine_soldier/vo/hunter.wav");
Schema.voices:Add("Combine", "Hurricane", "Hurricane!", "npc/combine_soldier/vo/hurricane.wav");
Schema.voices:Add("Combine", "Ice", "Ice!", "npc/combine_soldier/vo/ice.wav");
Schema.voices:Add("Combine", "Infected", "Infected.", "npc/combine_soldier/vo/infected.wav");
Schema.voices:Add("Combine", "Ion", "Ion!", "npc/combine_soldier/vo/ion.wav");
Schema.voices:Add("Combine", "Is at code..", "Is at code..", "npc/combine_soldier/vo/isatcode.wav");
Schema.voices:Add("Combine", "Is Field Promoted", "He is field promoted, until we are one holding.", "npc/combine_soldier/vo/isfieldpromoted.wav");
Schema.voices:Add("Combine", "Is Final Team Unit", "He is final team unit to push Backup.", "npc/combine_soldier/vo/isfinalteamunitbackup.wav");
Schema.voices:Add("Combine", "Is Holding Code", "He is holding at code..", "npc/combine_soldier/vo/isholdingatcode.wav");
Schema.voices:Add("Combine", "Jet", "Jet!", "npc/combine_soldier/vo/jet.wav");
Schema.voices:Add("Combine", "Leader", "Leader!", "npc/combine_soldier/vo/leader.wav");
Schema.voices:Add("Combine", "Meters2", "Meters!", "npc/combine_soldier/vo/meters.wav");
Schema.voices:Add("Combine", "Motion Check All Radials.", "Motion check all radials.", "npc/combine_soldier/vo/motioncheckallradials.wav");
Schema.voices:Add("Combine", "Niner", "Niner!", "npc/combine_soldier/vo/niner.wav");
Schema.voices:Add("Combine", "One Contained", "One Contained!", "npc/combine_soldier/vo/onecontained.wav");
Schema.voices:Add("Combine", "One Down", "One Down!", "npc/combine_soldier/vo/onedown.wav");
Schema.voices:Add("Combine", "One Duty Vacated", "One, Duty Vacated!", "npc/combine_soldier/vo/onedutyvacated.wav");
Schema.voices:Add("Combine", "One Hundred2", "One Hundred.", "npc/combine_soldier/vo/onehundred.wav");
Schema.voices:Add("Combine", "Overwatch Confirm HVT Contained", "Overwatch confirm human verdict to contained.", "npc/combine_soldier/vo/overwatchconfirmhvtcontained.wav");
Schema.voices:Add("Combine", "Overwatch Report Responsible Hostiles", "Overwatch report responsible hostiles, inbound.", "npc/combine_soldier/vo/overwatchreportspossiblehostiles.wav");
Schema.voices:Add("Combine", "Overwatch Request Reinforcement", "Overwatch request reinforcement.", "npc/combine_soldier/vo/overwatchrequestreinforcement.wav");
Schema.voices:Add("Combine", "Overwatch Request Reserve Activation", "Overwatch request reserve activation.", "npc/combine_soldier/vo/overwatchrequestreserveactivation.wav");
Schema.voices:Add("Combine", "Overwatch Request Sky Shield", "Overwatch request sky shield.", "npc/combine_soldier/vo/overwatchrequestskyshield.wav");
Schema.voices:Add("Combine", "Overwatch Request Winder Dispatch", "Overwatch request winder, dispatch.", "npc/combine_soldier/vo/overwatchrequestwinder.wav");
Schema.voices:Add("Combine", "Overwatch Sector Overrun", "Overwatch sector overrun, repeat sector overrun.", "npc/combine_soldier/vo/overwatchsectoroverrun.wav");
Schema.voices:Add("Combine", "Overwatch Orders 3cc Stimboost", "Overwatch orders 3cc stimboost.", "npc/combine_soldier/vo/ovewatchorders3ccstimboost.wav");
Schema.voices:Add("Combine", "Prep For Contact", "Prep for contact, report in!", "npc/combine_soldier/vo/prepforcontact.wav");
Schema.voices:Add("Combine", "Prosecuting", "Prosecuting.", "npc/combine_soldier/vo/prosecuting.wav");
Schema.voices:Add("Combine", "Quicksand", "Quicksand!", "npc/combine_soldier/vo/quicksand.wav");
Schema.voices:Add("Combine", "Range", "Range!", "npc/combine_soldier/vo/range.wav");
Schema.voices:Add("Combine", "Ready Extractors", "Ready extractors.", "npc/combine_soldier/vo/readyextractors.wav");
Schema.voices:Add("Combine", "Report All Positions Clear", "Report all positions clear.", "npc/combine_soldier/vo/reportallpositionsclear.wav");
Schema.voices:Add("Combine", "Report All Radials Free", "Report all radials free.", "npc/combine_soldier/vo/reportallradialsfree.wav");
Schema.voices:Add("Combine", "Reporting Clear", "Reporting clear.", "npc/combine_soldier/vo/reportingclear.wav");
Schema.voices:Add("Combine", "Request Medical", "Request medical!", "npc/combine_soldier/vo/requestmedical.wav");
Schema.voices:Add("Combine", "Request Stimdose", "Request stimdose!", "npc/combine_soldier/vo/requeststimdose.wav");
Schema.voices:Add("Combine", "Scar", "Scar!", "npc/combine_soldier/vo/scar.wav");
Schema.voices:Add("Combine", "Section Lock Up Dash 4", "Section lock up dash four.", "npc/combine_soldier/vo/sectionlockupdash4.wav");
Schema.voices:Add("Combine", "Sector Not Secure", "Sector is not secure.", "npc/combine_soldier/vo/sectorisnotsecure.wav");
Schema.voices:Add("Combine", "Secure", "Secure!", "npc/combine_soldier/vo/secure.wav");
Schema.voices:Add("Combine", "Sharp Zone", "Sharp Zone!", "npc/combine_soldier/vo/sharpzone.wav");
Schema.voices:Add("Combine", "Sight Line Clear", "Sight line is clear.", "npc/combine_soldier/vo/sightlineisclear.wav");
Schema.voices:Add("Combine", "Sky Shiled Reports Lost Contact", "Sky shield reports lost contact.", "npc/combine_soldier/vo/skyshieldreportslostcontact .wav");
Schema.voices:Add("Combine", "Slam", "Slam!", "npc/combine_soldier/vo/slam.wav");
Schema.voices:Add("Combine", "Slash", "Slash!", "npc/combine_soldier/vo/slash.wav");
Schema.voices:Add("Combine", "Stab", "Stab!", "npc/combine_soldier/vo/stab.wav");
Schema.voices:Add("Combine", "Stabilization Team Sector Control", "Stabilization team has sector control.", "npc/combine_soldier/vo/stabilizationteamhassector.wav");
Schema.voices:Add("Combine", "Stabilization Team Holding", "Stabilization team holding in position.", "npc/combine_soldier/vo/stabilizationteamholding.wav");
Schema.voices:Add("Combine", "Star", "Star!", "npc/combine_soldier/vo/star.wav");
Schema.voices:Add("Combine", "Stay Alert", "Stay alert.", "npc/combine_soldier/vo/stayalert.wav");
Schema.voices:Add("Combine", "Stay Alert Report Sight", "Stay alert, report sight lines.", "npc/combine_soldier/vo/stayalertreportsightlines.wav");
Schema.voices:Add("Combine", "Sundown", "Sundown!", "npc/combine_soldier/vo/sundown.wav");
Schema.voices:Add("Combine", "Suppressing", "Suppressing!", "npc/combine_soldier/vo/suppressing.wav");
Schema.voices:Add("Combine", "Swift", "Swift!", "npc/combine_soldier/vo/swift.wav");
Schema.voices:Add("Combine", "Target Blackout", "Target Blackout, sweep to resume.", "npc/combine_soldier/vo/targetblackout.wav");
Schema.voices:Add("Combine", "Target Is At", "Target is at...", "npc/combine_soldier/vo/targetisat.wav");
Schema.voices:Add("Combine", "Three Hundred2", "Three hundred.", "npc/combine_soldier/vo/threehundred.wav");
Schema.voices:Add("Combine", "Tracker", "Tracker!", "npc/combine_soldier/vo/tracker.wav");
Schema.voices:Add("Combine", "Two Hundred2", "Two hundred.", "npc/combine_soldier/vo/twohundred.wav");
Schema.voices:Add("Combine", "Uniform", "Uniform!", "npc/combine_soldier/vo/uniform.wav");
Schema.voices:Add("Combine", "Unit Is Closing", "Unit is closing.", "npc/combine_soldier/vo/unitisclosing.wav");
Schema.voices:Add("Combine", "Unit Is Inbound", "Unit is inbound.", "npc/combine_soldier/vo/unitisinbound.wav");
Schema.voices:Add("Combine", "Unit Is Moving In", "Unit is moving in.", "npc/combine_soldier/vo/unitismovingin.wav");
Schema.voices:Add("Combine", "Viscon", "Viscon!", "npc/combine_soldier/vo/viscon.wav");
Schema.voices:Add("Combine", "Visual Exogens", "Visual exogens!", "npc/combine_soldier/vo/visualonexogens.wav");
Schema.voices:Add("Combine", "Weapon Off Safe Prep Contact", "Weapons off safe, prep for contact.", "npc/combine_soldier/vo/weaponsoffsafeprepforcontact.wav");
Schema.voices:Add("Combine", "Have Free Parasites", "We have free parasites.", "npc/combine_soldier/vo/wehavefreeparasites.wav");
Schema.voices:Add("Combine", "Non Tagged Viromes2", "We have non tagged viromes.", "npc/combine_soldier/vo/wehavenontaggedviromes.wav");
Schema.voices:Add("Combine", "Winder", "Winder!", "npc/combine_soldier/vo/winder.wav");
Schema.voices:Add("Combine", "Now1", "Now!", "vo/trainyard/ba_thatbeer01.wav");

if (CLIENT) then
table.sort(Schema.voices.stored.normalVoices, function(a, b) return a.command < b.command; end);

 for k, v in pairs(Schema.voices.stored.normalVoices) do
  if v.faction == "Combine" then
   Clockwork.directory:AddCode("Civil Protection", [[
    <div class="auraInfoTitle">]]..string.upper(v.command)..[[</div>
    <div class="auraInfoText">]]..v.phrase..[[</div>
   ]], true);
 end;
end;
end;