local PLUGIN = PLUGIN;

-- Schema.voices:AddDispatch("Text that you need to type in", "Usage", ".wav");
Schema.voices:AddDispatch("404zone", "404zone.", "npc/overwatch/radiovoice/404zone.wav");
Schema.voices:AddDispatch("Accomplices Operating", "Protection Team verifired, accomplices operating an area.", "npc/overwatch/radiovoice/accomplicesoperating.wav");
Schema.voices:AddDispatch("Administer", "Administer.", "npc/overwatch/radiovoice/administer.wav");
Schema.voices:AddDispatch("Airwatchcopies Noactivity", "Airwatch copies is no activily in location.", "npc/overwatch/radiovoice/airwatchcopiesnoactivity.wav");
Schema.voices:AddDispatch("Airwatch Report Iscount", "Airwatch reports possiblem iscount.", "npc/overwatch/radiovoice/airwatchreportspossiblemiscount.wav");
Schema.voices:AddDispatch("62 Alarms", "62 Alarms.", "npc/overwatch/radiovoice/alarms62.wav");
Schema.voices:AddDispatch("Respond Code3", "All Team, respond code 3.", "npc/overwatch/radiovoice/allteamrespondcode3.wav");
Schema.voices:AddDispatch("Apply Pressure", "All unit, apply forward pressure.", "npc/overwatch/radiovoice/allunitapplyforwardpressure.wav");
Schema.voices:AddDispatch("Unit Sat", "All unit sat.", "npc/overwatch/radiovoice/allunitsat.wav");
Schema.voices:AddDispatch("Whitnesssterilization", "All units, begin with Whitnesssterilization.", "npc/overwatch/radiovoice/allunitsbeginwhitnesssterilization.wav");
Schema.voices:AddDispatch("Deliver Terminal Verdict", "All units, devlier terminal verdict immediately.", "npc/overwatch/radiovoice/allunitsdeliverterminalverdict.wav");
Schema.voices:AddDispatch("Return Code12", "All units, return to code 12.", "npc/overwatch/radiovoice/allunitsreturntocode12.wav");
Schema.voices:AddDispatch("Verdict Code", "All units, verdict code is...", "npc/overwatch/radiovoice/allunitsverdictcodeis.wav");
Schema.voices:AddDispatch("Verdict Codeon", "All units, verdict code on suspect", "npc/overwatch/radiovoice/allunitsverdictcodeonsuspect.wav");
Schema.voices:AddDispatch("Amputate", "Amputate.", "npc/overwatch/radiovoice/amputate.wav");
Schema.voices:AddDispatch("AntiCitizen", "Anti-Citizen.", "npc/overwatch/radiovoice/anticitizen.wav");
Schema.voices:AddDispatch("Apply", "Apply.", "npc/overwatch/radiovoice/apply.wav");
Schema.voices:AddDispatch("Attention", "Attention!", "npc/overwatch/radiovoice/attention.wav");
Schema.voices:AddDispatch("Block", "Block.", "npc/overwatch/radiovoice/block.wav");
Schema.voices:AddDispatch("Charged with", "Attention, you have been charged with...", "npc/overwatch/radiovoice/attentionyouhavebeenchargedwith.wav");
Schema.voices:AddDispatch("Canalblock", "Canalblock.", "npc/overwatch/radiovoice/canalblock.wav");
Schema.voices:AddDispatch("Capital Malcompliance", "Capital Malcompliance.", "npc/overwatch/radiovoice/capitalmalcompliance.wav");
Schema.voices:AddDispatch("Cauterize", "Cauterize.", "npc/overwatch/radiovoice/cauterize.wav");
Schema.voices:AddDispatch("Citizen", "Citizen.", "npc/overwatch/radiovoice/citizen.wav");
Schema.voices:AddDispatch("Condemned Zone", "Condemned Zone.", "npc/overwatch/radiovoice/condemnedzone.wav");
Schema.voices:AddDispatch("UPI Alert", "Team, confirm UPI alert.", "npc/overwatch/radiovoice/confirmupialert.wav");
Schema.voices:AddDispatch("63Trespass", "63 criminal trespass.", "npc/overwatch/radiovoice/criminaltrespass63.wav");
Schema.voices:AddDispatch("Defender", "Defender!", "npc/overwatch/radiovoice/defender.wav");
Schema.voices:AddDispatch("Restricted Block", "Restricted Block.", "npc/overwatch/radiovoice/deservicedarea.wav");
Schema.voices:AddDispatch("8", "Eight.", "npc/overwatch/radiovoice/eight.wav");
Schema.voices:AddDispatch("Examine", "Examine!", "npc/overwatch/radiovoice/examine.wav");
Schema.voices:AddDispatch("Failure To Comply", "Failure to comply with the civil will.", "npc/overwatch/radiovoice/failuretocomply.wav");
Schema.voices:AddDispatch("Final Verdict", "Final verdict administered", "npc/overwatch/radiovoice/finalverdictadministered.wav");
Schema.voices:AddDispatch("5", "Five.", "npc/overwatch/radiovoice/five.wav");
Schema.voices:AddDispatch("4", "Four.", "npc/overwatch/radiovoice/four.wav");
Schema.voices:AddDispatch("Freeman", "Freeman!", "npc/overwatch/radiovoice/freeman.wav");
Schema.voices:AddDispatch("Hero", "Hero!", "npc/overwatch/radiovoice/hero.wav");
Schema.voices:AddDispatch("High Priority Region", "High Priority region.", "npc/overwatch/radiovoice/highpriorityregion.wav");
Schema.voices:AddDispatch("Industrial Zone", "Industrial zone.", "npc/overwatch/radiovoice/industrialzone.wav");
Schema.voices:AddDispatch("Infect", "Infection.", "npc/overwatch/radiovoice/infection.wav");
Schema.voices:AddDispatch("Infested Zone", "Infested Zone.", "npc/overwatch/radiovoice/infestedzone.wav");
Schema.voices:AddDispatch("Lock", "Lock!", "npc/overwatch/radiovoice/lock.wav");
Schema.voices:AddDispatch("Inject", "Inject!", "npc/overwatch/radiovoice/inject.wav");
Schema.voices:AddDispatch("Innoculate", "Innoculate!", "npc/overwatch/radiovoice/innoculate.wav");
Schema.voices:AddDispatch("In Progress", "In Progress.", "npc/overwatch/radiovoice/inprogress.wav");
Schema.voices:AddDispatch("Interlock", "Interlock!", "npc/overwatch/radiovoice/interlock.wav");
Schema.voices:AddDispatch("Investigate", "Investigate.", "npc/overwatch/radiovoice/investigate.wav");
Schema.voices:AddDispatch("Investigate And Report", "Investigate and report!", "npc/overwatch/radiovoice/investigateandreport.wav");
Schema.voices:AddDispatch("Is Now", "Is now.", "npc/overwatch/radiovoice/isnow.wav");
Schema.voices:AddDispatch("Isolate", "Isolate.", "npc/overwatch/radiovoice/isolate.wav");
Schema.voices:AddDispatch("Jury", "Jury!", "npc/overwatch/radiovoice/jury.wav");
Schema.voices:AddDispatch("King", "King!", "npc/overwatch/radiovoice/king.wav");
Schema.voices:AddDispatch("Line", "Line!", "npc/overwatch/radiovoice/line.wav");
Schema.voices:AddDispatch("Lockdown Location", "Protection Team, lockdown your location sacrifice code.", "npc/overwatch/radiovoice/lockdownlocationsacrificecode.wav");
Schema.voices:AddDispatch("Biosignal Lost", "Lost Biosignal for protection team unit.", "npc/overwatch/radiovoice/lostbiosignalforunit.wav");
Schema.voices:AddDispatch("Nine", "Nine.", "npc/overwatch/radiovoice/nine.wav");
Schema.voices:AddDispatch("Noncitizen", "Non Citizen.", "npc/overwatch/radiovoice/noncitizen.wav");
Schema.voices:AddDispatch("Non Patrol Region", "Non patrol region!", "npc/overwatch/radiovoice/nonpatrolregion.wav");
Schema.voices:AddDispatch("Officer At", "Officer at...", "npc/overwatch/radiovoice/officerat.wav");
Schema.voices:AddDispatch("Officer Closing On Suspect", "Officer closing on suspect.", "npc/overwatch/radiovoice/officerclosingonsuspect.wav");
Schema.voices:AddDispatch("1", "One.", "npc/overwatch/radiovoice/one.wav");
Schema.voices:AddDispatch("OFF2", "*Radio turns off*", "npc/overwatch/radiovoice/off2.wav");
Schema.voices:AddDispatch("OFF4", "*Radio goes off*", "npc/overwatch/radiovoice/off4.wav");
Schema.voices:AddDispatch("ON1", "*Radio goes on*", "npc/overwatch/radiovoice/on1.wav");
Schema.voices:AddDispatch("ON3", "*Radio turns on*", "npc/overwatch/radiovoice/on3.wav");
Schema.voices:AddDispatch("Outlandzone", "Outlandzone.", "npc/overwatch/radiovoice/outlandzone.wav");
Schema.voices:AddDispatch("Patrol", "Patrol!", "npc/overwatch/radiovoice/patrol.wav");
Schema.voices:AddDispatch("Preserve", "Preserve.", "npc/overwatch/radiovoice/preserve.wav");
Schema.voices:AddDispatch("69 posession", "69 posession of recources.", "npc/overwatch/radiovoice/posession69.wav");
Schema.voices:AddDispatch("Pressure", "Pressure.", "npc/overwatch/radiovoice/pressure.wav");
Schema.voices:AddDispatch("Production Block", "Prdouction block.", "npc/overwatch/radiovoice/production block.wav");
Schema.voices:AddDispatch("Promoting Unrest", "Promoting communal unrest.", "npc/overwatch/radiovoice/promotingcommunalunrest.wav");
Schema.voices:AddDispatch("Prosecute", "Prosecute.", "npc/overwatch/radiovoice/prosecute.wav");
Schema.voices:AddDispatch("Quick", "Quick!", "npc/overwatch/radiovoice/quick.wav");
Schema.voices:AddDispatch("Recalibrate Scan", "Team, recalibrate socio scan.", "npc/overwatch/radiovoice/recalibratesocioscan.wav");
Schema.voices:AddDispatch("Recieving Conflicting Data", "We are recieving conflicting data.", "npc/overwatch/radiovoice/recievingconflictingdata.wav");
Schema.voices:AddDispatch("Reinforcment Code3", "Reinforment Team, Code 3.", "npc/overwatch/radiovoice/reinforcmentteamtcode3.wav");
Schema.voices:AddDispatch("Remaining Units Contain", "Remaining units contain.", "npc/overwatch/radiovoice/remainingunitscontain.wav");
Schema.voices:AddDispatch("Report On", "Local protection team units, report on.", "npc/overwatch/radiovoice/reporton.wav");
Schema.voices:AddDispatch("Report Please", "Report... please!", "npc/overwatch/radiovoice/reportplease.wav");
Schema.voices:AddDispatch("repurosedarea", "Repurosed Area.", "npc/overwatch/radiovoice/repurosedarea.wav");
Schema.voices:AddDispatch("Residential Block", "Residential Block.", "npc/overwatch/radiovoice/residentialblock.wav");
Schema.voices:AddDispatch("Respond", "Respond.", "npc/overwatch/radiovoice/respond.wav");
Schema.voices:AddDispatch("Restrict", "Restrict.", "npc/overwatch/radiovoice/restrict.wav");
Schema.voices:AddDispatch("Reward Notice", "Reward notice, protection team member your family cohesion.", "npc/overwatch/radiovoice/rewardnotice.wav");
Schema.voices:AddDispatch("404riot", "404 Riot.", "npc/overwatch/radiovoice/riot404.wav");
Schema.voices:AddDispatch("Roller", "Roller!", "npc/overwatch/radiovoice/roller.wav");
Schema.voices:AddDispatch("Search", "Search.", "npc/overwatch/radiovoice/search.wav");
Schema.voices:AddDispatch("Sector", "Sector!", "npc/overwatch/radiovoice/sector.wav");
Schema.voices:AddDispatch("Serve", "Serve!", "npc/overwatch/radiovoice/serve.wav");
Schema.voices:AddDispatch("7", "Seven.", "npc/overwatch/radiovoice/seven.wav");
Schema.voices:AddDispatch("6", "Six.", "npc/overwatch/radiovoice/six.wav");
Schema.voices:AddDispatch("Sociocide", "Sociocide.", "npc/overwatch/radiovoice/sociocide.wav");
Schema.voices:AddDispatch("Social Fracture Progress", "Social fracture in progress, respond.", "npc/overwatch/radiovoice/socialfractureinprogress.wav");
Schema.voices:AddDispatch("Socio Restored", "Socio abilization restored.", "npc/overwatch/radiovoice/socioabilizationrestored.wav");
Schema.voices:AddDispatch("Station Block", "Station Block!", "npc/overwatch/radiovoice/stationblock.wav");
Schema.voices:AddDispatch("Sterilize", "Sterilize.", "npc/overwatch/radiovoice/sterilize.wav");
Schema.voices:AddDispatch("Stick", "Stick!", "npc/overwatch/radiovoice/stick.wav");
Schema.voices:AddDispatch("Storm System", "Storm System.", "npc/overwatch/radiovoice/stormsystem.wav");
Schema.voices:AddDispatch("Subject", "Subject!", "npc/overwatch/radiovoice/subject.wav");
Schema.voices:AddDispatch("Suspend", "Suspend.", "npc/overwatch/radiovoice/suspend.wav");
Schema.voices:AddDispatch("Tap", "Tap.", "npc/overwatch/radiovoice/tap.wav");
Schema.voices:AddDispatch("Report Status", "Local Civil Protection team, report status.", "npc/overwatch/radiovoice/teamreportstatus.wav");
Schema.voices:AddDispatch("3", "Three", "npc/overwatch/radiovoice/three.wav");
Schema.voices:AddDispatch("Transit Block", "Transit Block.", "npc/overwatch/radiovoice/transitblock.wav");
Schema.voices:AddDispatch("2", "Two.", "npc/overwatch/radiovoice/two.wav");
Schema.voices:AddDispatch("Union", "Union!", "npc/overwatch/radiovoice/union.wav");
Schema.voices:AddDispatch("Unit Deserviced", "Unit Deserviced.", "npc/overwatch/radiovoice/unitdeserviced.wav");
Schema.voices:AddDispatch("Unit Down At", "Unit down at...", "npc/overwatch/radiovoice/unitdownat.wav");
Schema.voices:AddDispatch("UPI", "UPI.", "npc/overwatch/radiovoice/upi.wav");
Schema.voices:AddDispatch("Vice", "Vice!", "npc/overwatch/radiovoice/vice.wav");
Schema.voices:AddDispatch("Victor", "Victor!", "npc/overwatch/radiovoice/victor.wav");
Schema.voices:AddDispatch("Violation Of Civil Trust", "Violation of Civil trust.", "npc/overwatch/radiovoice/violationofciviltrust.wav");
Schema.voices:AddDispatch("Waste river", "Waste river.", "npc/overwatch/radiovoice/wasteriver.wav");
Schema.voices:AddDispatch("94 Weapon", "94 Weapon.", "npc/overwatch/radiovoice/weapon94.wav");
Schema.voices:AddDispatch("Work Force Intake", "Work force intake hub.", "npc/overwatch/radiovoice/workforceintake.wav");
Schema.voices:AddDispatch("Xray", "X-Ray!", "npc/overwatch/radiovoice/xray.wav");
Schema.voices:AddDispatch("Yellow", "Yellow!", "npc/overwatch/radiovoice/yellow.wav");
Schema.voices:AddDispatch("0", "Zero.", "npc/overwatch/radiovoice/zero.wav");
Schema.voices:AddDispatch("Zone", "Zone!", "npc/overwatch/radiovoice/zone.wav");
Schema.voices:AddDispatch("Judged Guilty", "You are Judged guilty, civil protection team.", "npc/overwatch/radiovoice/youarejudgedguilty.wav");
Schema.voices:AddDispatch("Unregistered Weapons", "Security alert. Unregistered weapons detected. Confiscation field engaged.", "npc/overwatch/cityvoice/fcitadel_confiscating.wav");
Schema.voices:AddDispatch("Confsication Failure", "Warning. Counter-resonant singularity device detected. Confiscation field failure.", "npc/overwatch/cityvoice/fcitadel_confiscationfailure.wav");
Schema.voices:AddDispatch("Illegal Device Dedected", "Security alert. Illegal counter-resonant singularity device detected. Deploy, diagnose, dissect.", "npc/overwatch/cityvoice/fcitadel_deploy.wav");
Schema.voices:AddDispatch("Transport Sequence", "Attention. Transport singularity interlock sequence engaged.", "npc/overwatch/cityvoice/fcitadel_transportsequence.wav");
Schema.voices:AddDispatch("3m Singularity", "Warning. Three minutes to singularity.", "npc/overwatch/cityvoice/fcitadel_3minutestosingularity.wav");
Schema.voices:AddDispatch("2m Singularity", "Warning. Two minutes to singularity.", "npc/overwatch/cityvoice/fcitadel_2minutestosingularity.wav");
Schema.voices:AddDispatch("1m Singularity", "Warning. One minutes to singularity.", "npc/overwatch/cityvoice/fcitadel_1minutestosingularity.wav");
Schema.voices:AddDispatch("45s Singularity", "Priority warning. Forty five seconds to singularity.", "npc/overwatch/cityvoice/fcitadel_45sectosingularity.wav");
Schema.voices:AddDispatch("30s Singularity", "Priority warning. Thirty five seconds to singularity.", "npc/overwatch/cityvoice/fcitadel_30sectosingularity.wav");
Schema.voices:AddDispatch("15s Singularity", "Priority warning. Fifteen seconds to singularity.", "npc/overwatch/cityvoice/fcitadel_15sectosingularity.wav");
Schema.voices:AddDispatch("10s Singularity", "Priority warning. Ten seconds to singularity.", "npc/overwatch/cityvoice/fcitadel_10sectosingularity.wav");
Schema.voices:AddDispatch("Nonstandart Exogen", "Alert. Non-standard exogen activity detected. Execute containment procedure and report.", "npc/overwatch/cityvoice/fprison_nonstandartexogen.wav");
Schema.voices:AddDispatch("Freeman Located", "Incursion warning. Airwatch reports probable Anticitizen Freeman reacquired zone Nova Prospekt. Ground units deprioritize exogen containment. Hold for override codes.", "npc/overwatch/cityvoice/fprison_freemanlocated.wav");
Schema.voices:AddDispatch("Radio Random 1", "*Radio bad connection sound*", "ambient/levels/prison/radio_random1.wav");
Schema.voices:AddDispatch("Radio Random 2", "*Radio bad connection sounds*", "ambient/levels/prison/radio_random2.wav");
Schema.voices:AddDispatch("Radio Random 3", "*Radio bad connection sounds*", "ambient/levels/prison/radio_random3.wav");
Schema.voices:AddDispatch("Radio Random 4", "*Radio bad connection sounds*", "ambient/levels/prison/radio_random4.wav");
Schema.voices:AddDispatch("Radio Random 5", "*Radio bad connection sounds*", "ambient/levels/prison/radio_random5.wav");
Schema.voices:AddDispatch("Radio Random 6", "*Radio bad connection sounds*", "ambient/levels/prison/radio_random6.wav");
Schema.voices:AddDispatch("Radio Random 7", "*Radio sounds*", "ambient/levels/prison/radio_random7.wav");
Schema.voices:AddDispatch("Radio Random 8", "*Radio sounds*", "ambient/levels/prison/radio_random8.wav");
Schema.voices:AddDispatch("Radio Random 9", "*Radio sounds*", "ambient/levels/prison/radio_random9.wav");
Schema.voices:AddDispatch("Radio Random 10", "*Radio sounds*", "ambient/levels/prison/radio_random10.wav");
Schema.voices:AddDispatch("Radio Random 11", "*Radio sounds*", "ambient/levels/prison/radio_random11.wav");
Schema.voices:AddDispatch("Radio Random 12", "*Radio sounds*", "ambient/levels/prison/radio_random12.wav");
Schema.voices:AddDispatch("Radio Random 13", "*Radio sounds*", "ambient/levels/prison/radio_random13.wav");
Schema.voices:AddDispatch("Radio Random 14", "*Radio sounds*", "ambient/levels/prison/radio_random14.wav");
Schema.voices:AddDispatch("Radio Random 15", "*Radio sounds*", "ambient/levels/prison/radio_random15.wav");
Schema.voices:AddDispatch("AntiCivilLev1", "You are charged with anti-civil activity level one. Protection unit prosecution code: duty, sword, operate.", "npc/overwatch/cityvoice/f_anticivil1_5_spkr.wav");
Schema.voices:AddDispatch("Capitalmalcompliance", "Individual, you are charged with capital malcompliance. Anti-citizen status approved.", "npc/overwatch/cityvoice/f_capitalmalcompliance_spkr.wav");
Schema.voices:AddDispatch("socio-endangermentLev5", "Individual, you are now charged with socio-endangerment level five, cease evasion immediately. Receive your verdict.", "npc/overwatch/cityvoice/f_ceaseevasionlevelfive_spkr.wav");
Schema.voices:AddDispatch("Evasion behavior", "Attention please. Evasion behavior consistent with malcompliant defendant. Ground protection team alert. Code: isolate, expose, administer.", "npc/overwatch/cityvoice/f_evasionbehavior_2_spkr.wav");
Schema.voices:AddDispatch("Protectionresponse1", "Attention protection team, status evasion in progress in this community. Respond, isolate, inquire.", "npc/overwatch/cityvoice/f_protectionresponse_1_spkr.wav");
Schema.voices:AddDispatch("Rationunitsdeduct", "Attention occupants, your block is now charged with permissive inactive coercion. Five ration units deducted.", "npc/overwatch/cityvoice/f_rationunitsdeduct_3_spkr.wav");
Schema.voices:AddDispatch("socio-endangermentLev4", "Individual, you are charged with socio-endangerment level one. Protection units prosecution code: duty, sword, midnight.", "npc/overwatch/cityvoice/f_sociolevel1_4_spkr.wav");
Schema.voices:AddDispatch("cooperationmiscount", "Attention residents, miscount detected in your block. Co-operation with your Civil Protection team permit full ration reward.", "npc/overwatch/cityvoice/f_trainstation_cooperation_spkr.wav");
Schema.voices:AddDispatch("Informblock", "Attention residents, this block contains potential civil infection. Inform, co-operate, assemble.", "npc/overwatch/cityvoice/f_trainstation_inform_spkr.wav");
Schema.voices:AddDispatch("Contactland-sea", "Alert. Contact status zero with land-sea intercept teams. Possible Anticitizen One re-infection. All Nova Prospekt stabilization delegates move to hard point.", "npc/overwatch/cityvoice/fprison_contactlostlandsea.wav");
Schema.voices:AddDispatch("fprison_ContainExogens", "Nova Prospekt stabilization force directive two, engage reserve. Contain exogen incursion.", "npc/overwatch/cityvoice/fprison_containexogens.wav");
Schema.voices:AddDispatch("Deployinb4", "Contact lost in block B2. Deploy, reinforce, intercept in central block B4.", "npc/overwatch/cityvoice/fprison_deployinb4.wav");
Schema.voices:AddDispatch("fprison_DeservicePoliticalConscripts", "Attention Nova Prospekt internal containment team. De-service all political conscripts in block A7. Prohibit external contact.", "npc/overwatch/cityvoice/fprison_deservicepoliticalconscripts.wav");
Schema.voices:AddDispatch("DetectionSystemsOut", "Warning, surveillance and detection systems inactive. Remaining stabilization team members report containment status please.", "npc/overwatch/cityvoice/fprison_detectionsystemsout.wav");
Schema.voices:AddDispatch("fprison_DropForceSixAndEight", "-", "npc/overwatch/cityvoice/fprison_dropforcesixandeight.wav");
Schema.voices:AddDispatch("fprison_Interfacebypass", "Warning, malignant viral interface bypass detected. Polyphasic core reprogramming detected. Sterilizers and containment fields may be compromised.", "npc/overwatch/cityvoice/fprison_interfacebypass.wav");
Schema.voices:AddDispatch("PerimeterRestrictors", "Priority warning. Outland stabilization force six Nova Prospekt. Perimeter restrictors disengaged. Priority warning, perimeter restrictors disengaged.", "npc/overwatch/cityvoice/fprison_perimeterrestrictors.wav");
Schema.voices:AddDispatch("RestrictorDisenganged", "Priority warning, perimeter restrictors disengaged. All stabilization delegates move to incursion hard points immediately.", "npc/overwatch/cityvoice/fprison_restrictorsdisengaged.wav");
Schema.voices:AddDispatch("fcitadel_alertx3", "Alert, Alert, Alert", "ambient/levels/citadel/fcitadel_alert.wav");
Schema.voices:AddDispatch("fcitadel_alertx1", "Alert", "ambient/levels/citadel/fcitadel_alert2.wav");
Schema.voices:AddDispatch("fcitadel_BypassDetected", "Warning: Bypass detected", "ambient/levels/citadel/fcitadel_bypassdetected.wav");
Schema.voices:AddDispatch("fcitadel_Corereprogramming", "Warning: Core reprogramming detected.", "ambient/levels/citadel/fcitadel_corereprogramming1.wav");
Schema.voices:AddDispatch("fcitadel_DeployDiagnose", "Deploy, diagnose, deploy, diagnose. Resonant singularity, resonant singularity.", "ambient/levels/citadel/fcitadel_deploydiagnose.wav");
Schema.voices:AddDispatch("fcitadel_DeploySterilizers", "Priority alert: Internal stabilization teams - deploy sterilizers. Deploy.", "ambient/levels/citadel/fcitadel_deploysterilizers.wav");
Schema.voices:AddDispatch("fcitadel_RestrictorsDisengaged", "Priority warning: Restrictors disengaged.", "ambient/levels/citadel/fcitadel_restrictorsdisengaged.wav");
Schema.voices:AddDispatch("fcitadel_StabilizationDisengaged", "Stabilisation force disengaged.", "ambient/levels/citadel/fcitadel_stabilization_disengaged1.wav");
Schema.voices:AddDispatch("fcitadel_SterilizersCompromized", "Sterilizers and containment fields compromised.", "ambient/levels/citadel/fcitadel_sterilizerscompromized.wav");
Schema.voices:AddDispatch("advisor_enter_loop1", "*Lift Machine*", "ambient/levels/citadel/advisor_enter_loop.wav");
Schema.voices:AddDispatch("advisor_leave1", "*Machine Deploy*", "ambient/levels/citadel/advisor_leave.wav");
Schema.voices:AddDispatch("advisor_lift1", "*Lift Machine*", "ambient/levels/citadel/advisor_lift.wav");
Schema.voices:AddDispatch("citadel_5sirens", "*Gareeng, Gareeng, Gareeng, Gareeng, Gareeng, Gareeng*", "ambient/levels/citadel/citadel_5sirens.wav");
Schema.voices:AddDispatch("citadel_5sirens2", "*Citadel Siren*", "ambient/levels/citadel/citadel_5sirens2.wav");
Schema.voices:AddDispatch("citadel_5sirens3", "*Citadel Siren*", "ambient/levels/citadel/citadel_5sirens3.wav");
Schema.voices:AddDispatch("citadel_alarmdrone_loop1", "*Alarmdrone loop*", "ambient/levels/citadel/citadel_alarmdrone_loop1.wav");
Schema.voices:AddDispatch("citadel_coregrind_loop1", "*Coregrind loop*", "ambient/levels/citadel/citadel_coregrind_loop1.wav");
Schema.voices:AddDispatch("citadel_coregrind_loop2", "*Coregrind loop*", "ambient/levels/citadel/citadel_coregrind_loop2.wav");
Schema.voices:AddDispatch("citadel_coregrind_loop3", "*Coregrind loop*", "ambient/levels/citadel/citadel_coregrind_loop3.wav");
Schema.voices:AddDispatch("citadel_sickdrone_loop1", "*Sickdrone loop*", "ambient/levels/citadel/citadel_sickdrone_loop1.wav");
Schema.voices:AddDispatch("citadel_sickdrone_loop2", "*Sickdrone loop*", "ambient/levels/citadel/citadel_sickdrone_loop2.wav");
Schema.voices:AddDispatch("citadel_sickdrone_loop3", "*Sickdrone loop*", "ambient/levels/citadel/citadel_sickdrone_loop3.wav");
Schema.voices:AddDispatch("citadel_sickdrone_loop4", "*Sickdrone loop*", "ambient/levels/citadel/citadel_sickdrone_loop4.wav");
Schema.voices:AddDispatch("citadel_sickcore_loop5", "*Sickcore loop*", "ambient/levels/citadel/citadel_sickcore_loop5.wav");
Schema.voices:AddDispatch("datatransfmalevx01", "*Unknow Speaker*", "ambient/levels/citadel/datatransfmalevx01.wav");
Schema.voices:AddDispatch("datatransfmalevx02", "*Unknow Speaker*", "ambient/levels/citadel/datatransfmalevx02.wav");
Schema.voices:AddDispatch("datatransgarbledfmalevx01", "*Unknow Speaker*", "ambient/levels/citadel/datatransgarbledfmalevx01.wav");
Schema.voices:AddDispatch("datatransmalevx01", "*Unknow...*", "ambient/levels/citadel/datatransmalevx01.wav");
Schema.voices:AddDispatch("datatransmalevx02", "*Unknow...*", "ambient/levels/citadel/datatransmalevx02.wav");
Schema.voices:AddDispatch("datatransmission01_loop", "*Data Transmission Loop*", "ambient/levels/citadel/datatransmission01_loop.wav");
Schema.voices:AddDispatch("datatransmission02_loop", "*Data Transmission Loop*", "ambient/levels/citadel/datatransmission02_loop.wav");
Schema.voices:AddDispatch("datatransmission03_loop", "*Data Transmission Loop*", "ambient/levels/citadel/datatransmission03_loop.wav");
Schema.voices:AddDispatch("datatransmission04_loop", "*Data Transmission Loop*", "ambient/levels/citadel/datatransmission04_loop.wav");
Schema.voices:AddDispatch("datatransrandom01", "*Unknow...*", "ambient/levels/citadel/datatransrandom01.wav");
Schema.voices:AddDispatch("datatransrandom02", "*Unknow...*", "ambient/levels/citadel/datatransrandom02.wav");
Schema.voices:AddDispatch("datatransrandom03", "*Unknow...*", "ambient/levels/citadel/datatransrandom03.wav");
Schema.voices:AddDispatch("advisor_blast1", "*Advisor Blast*", "npc/advisor/advisor_blast1.wav");
Schema.voices:AddDispatch("advisor_blast6", "*Advisor Blast*", "npc/advisor/advisor_blast6.wav");
Schema.voices:AddDispatch("advisor_scream1", "*Advisor Scream*", "npc/advisor/advisor_scream.wav");
Schema.voices:AddDispatch("OUTLAND_over_camp", "Ongoing sector sweep, biotics confirmed. Continue surface sector sweep, remote compliance, exterminate. Seek passive signature imprint. Mandate sublevel restrictions.", "vo/outland_01/intro/over_camp.wav");
Schema.voices:AddDispatch("OUTLAND_over_vista", "All autonomous units, accept mandatory sector assimilation. Co-ordinate constriction underway. Debride and cauterize. Entering Phase nine, enhanced compliance. Deploy advisory control and oversight. Submit and be subsumed.", "vo/outland_05/canyon/over_vista.wav");
Schema.voices:AddDispatch("OUTLAND_over_barn", "Vital alert. Autonomous units subsumed. Mandatory compliance with all tenets of advisorial assistance act. Threat level adjustment. Probe. Expunge.", "vo/outland_07/barn/over_barn.wav");
Schema.voices:AddDispatch("OUTLAND_over_inne", "Alert, anticitizen one engaged. Vance Subprime engaged. Expunge. Mandate removal of active signature imprint. Cauterize and expunge.", "vo/outland_/olde-inne/over_inne.wav");
Schema.voices:AddDispatch("hl2_song19", "[OOC](Music Playing: Nova Prospekt *Clockwork Menu*)", "music/hl2_song19.mp3");
Schema.voices:AddDispatch("fcitadel_finale1", "*Citadel Explosion*", "ambient/outro/citadelfinale.wav");
Schema.voices:AddDispatch("fcitadel_pan1", "*Citadel Pan*", "ambient/intro/citadelpan.wav");
Schema.voices:AddDispatch("hl2_song1", "[OOC](Music Playing: Particle Ghost)", "music/hl2_song1.mp3");
Schema.voices:AddDispatch("hl2_song20_submix0", "[OOC](Music Playing: CP Violation)", "music/hl2_song20_submix0.mp3");
Schema.voices:AddDispatch("hl2_song29", "[OOC](Music Playing: Apprehension and Evasion)", "music/hl2_song29.mp3");
Schema.voices:AddDispatch("hl2_ravenholm_1", "[OOC](Music Playing: Requiem For Ravenholm)", "music/ravenholm_1.mp3");
Schema.voices:AddDispatch("hl2_radio1", "[OOC](Music Playing: Radio)", "music/radio1.mp3");
Schema.voices:AddDispatch("hl1_song3", "[OOC](Music Playing: *A hl1 song*)", "music/hl1_song3.mp3");
Schema.voices:AddDispatch("hl2_song3", "[OOC](Music Playing: Dark Energy)", "music/hl2_song3.mp3");
Schema.voices:AddDispatch("vlvx_song11", "[OOC](Music Playing: Disrupted Original)", "music/vlvx_song11.mp3");
Schema.voices:AddDispatch("vlvx_song18", "[OOC](Music Playing: What Kind of Hospital is This?)", "music/vlvx_song18.mp3");
Schema.voices:AddDispatch("vlvx_song22", "[OOC](Music Playing: Vortal Combat)", "music/vlvx_song22.mp3");
Schema.voices:AddDispatch("vlvx_song27", "[OOC](Music Playing: Hunting Party)", "music/vlvx_song27.mp3");
Schema.voices:AddDispatch("hl2_song23_suitsong3", "[OOC](Music Playing: Triages at Dawn, Path of Borealis)", "music/hl2_song23_suitsong3.mp3");

if (CLIENT) then
	table.sort(Schema.voices.stored.dispatchVoices, function(a, b) return a.command < b.command; end);

	for k, v in pairs(Schema.voices.stored.dispatchVoices) do
		Clockwork.directory:AddCode("Combine Dispatcher", [[
			<div class="auraInfoTitle">]]..string.upper(v.command)..[[</div>
			<div class="auraInfoText">]]..v.phrase..[[</div>
		]], true);
	end;
end;