local ITEM = Clockwork.item:New("weapon_base");
	ITEM.name = "Kalishnikov AK47";
	ITEM.cost = 0;
	ITEM.model = "models/weapons/3_rif_ak47.mdl";
	ITEM.weight = 3;
	ITEM.uniqueID = "bb_ak47_alt";
	ITEM.business = false;
	ITEM.description = "An assault rifle coated in various shades of orange, with a sleek wooden handle.";
	ITEM.isAttachment = true;
	ITEM.loweredOrigin = Vector(3, 0, -4);
	ITEM.loweredAngles = Angle(0, 45, 0);
	ITEM.attachmentBone = "ValveBiped.Bip01_Spine";
	ITEM.attachmentOffsetAngles = Angle(0, 0, 0);
	ITEM.attachmentOffsetVector = Vector(-4, 4, 4);
ITEM:Register();