local ITEM = Clockwork.item:New("grenade_base");
	ITEM.name = "Frag";
	ITEM.cost = 25;
	ITEM.classes = {CLASS_EMP, CLASS_EOW};
	ITEM.model = "models/weapons/w_eq_fraggrenade.mdl";
	ITEM.weight = 0.8;
	ITEM.uniqueID = "bb_cssfrag_alt";
	ITEM.business = true;
	ITEM.description = "A green ball that sounds hollow. You sure this explodes?";
	ITEM.isAttachment = true;
	ITEM.loweredOrigin = Vector(3, 0, -4);
	ITEM.loweredAngles = Angle(0, 45, 0);
	ITEM.attachmentBone = "ValveBiped.Bip01_Pelvis";
	ITEM.attachmentOffsetAngles = Angle(90, 0, 0);
	ITEM.attachmentOffsetVector = Vector(0, 6.55, 8.72);
ITEM:Register();