local ITEM = Clockwork.item:New("weapon_base");
	ITEM.name = "M249 Para";
	ITEM.cost = 0;
	ITEM.model = "models/weapons/3_mach_m249para.mdl";
	ITEM.weight = 7;
	ITEM.uniqueID = "bb_m249_alt";
	ITEM.business = false;
	ITEM.description = "A heavy weapon. Why do they call these things LIGHT machine guns!!?";
	ITEM.isAttachment = true;
	ITEM.loweredOrigin = Vector(3, 0, -4);
	ITEM.loweredAngles = Angle(0, 45, 0);
	ITEM.attachmentBone = "ValveBiped.Bip01_Spine";
	ITEM.attachmentOffsetAngles = Angle(0, 0, 0);
	ITEM.attachmentOffsetVector = Vector(-4, 4, 4);
ITEM:Register();