local ITEM = Clockwork.item:New("weapon_base");
	ITEM.name = "UMP 45";
	ITEM.cost = 0;
	ITEM.model = "models/weapons/3_smg_ump45.mdl";
	ITEM.weight = 3;
	ITEM.uniqueID = "bb_ump45_alt";
	ITEM.business = false;
	ITEM.description = "A generic SMG coated in a dull grey.";
	ITEM.isAttachment = true;
	ITEM.loweredOrigin = Vector(3, 0, -4);
	ITEM.loweredAngles = Angle(0, 45, 0);
	ITEM.attachmentBone = "ValveBiped.Bip01_Spine";
	ITEM.attachmentOffsetAngles = Angle(0, 0, 0);
	ITEM.attachmentOffsetVector = Vector(-4, 4, 4);
ITEM:Register();